### ISSUE TITLE
Text cursor does not change with colour scheme

### ISSUE THREAD

**Issue by Alaneor** [atom-material/atom-material-ui#171]
It seems that the cursor is always in the "teal" colour scheme, no matter what scheme I choose.

It would be nice to have the cursor change the colour to whatever primary colour I pick, if that's possible with Atom.

**Comment by WoodyWoodsta** [comment]
I think it is. Seen it with multiple other themes and syntaxes!

**Comment by silvestreh** [comment]
The cursor's color is defined within the syntax theme. I just tried setting `@syntax-cursor-color` to match `@base-color` inside the UI theme without any luck.

**Comment by silvestreh** [comment]
Just pushed an update for this. Though it requires an Atom restart (or reload).

**Comment by Alaneor** [comment]
It still seems to be teal. I am also using the material syntax. Material UI currently checked out at this commit - 42a2d70 (0.8.1).

![screen shot 2016-01-28 at 23 28 34](https://cloud.githubusercontent.com/assets/3058150/12661008/793112c4-c617-11e5-842a-5515996e1050.png)

**Comment by silvestreh** [comment]
@Alaneor this was meant to be used with the development version. Anyway, I reverted the change as it was messing things up with other UI themes. I'll reopen the issue to remind myself to keep investigating about it.

**Comment by Alaneor** [comment]
I just managed to successfully override my cursor colour using this less override via *styles.less*:

```less
.editor::shadow {
  .cursor {
    border-color: #ffd54f;
  }
}
```

Perhaps this can help you to integrate cursor overrides directly into the theme so that it always reflects the colour pallete selected by users?

Thanks!

**Comment by silvestreh** [comment]
Yep that should work…

**Comment by silvestreh** [comment]
Also… check what happens when I pick a light `base-color` with a light syntax theme

![captura de pantalla 2016-03-18 a las 16 11 45](https://cloud.githubusercontent.com/assets/1133339/13889243/421f28dc-ed24-11e5-98c6-a9e7521f3325.png)

(cursor is at the end of line)

**Comment by Alaneor** [comment]
Ouh... Well, that's... unfortunate. Not sure how to tackle that. Maybe then not pick the `@base-color` but the colour of the highlight? Like the light yellow you have on the tab bar. I guess that would improve things a bit. A tiny bit.

**Comment by silvestreh** [comment]
I'd probably need to write a mixin guard and compare both colors' brightness. I'll work something out.

**Comment by kozyablo** [comment]
It also seems that bottom color of bracket highlighter always has it's "teal" color scheme as well.
![screenshot from 2016-03-19 13 11 11](https://cloud.githubusercontent.com/assets/7263939/13897954/59f02c94-edd4-11e5-9162-37137d699071.png)

**Comment by Alaneor** [comment]
Indeed. That one can be overriden with this piece of *less*:

```less
.editor::shadow {
  .bracket-matcher .region {
    // Apply your tastes
    border: 1px solid;
    border-color: fade(@primary-color, 60%);
    border-radius: 3px;
    background-color: fade(@primary-color, 10%);
  }
}
```

![screen shot 2016-03-19 at 13 41 50](https://cloud.githubusercontent.com/assets/3058150/13898654/6185b8e4-edd8-11e5-89fe-7c32a11ec177.png)
