### ISSUE TITLE
Rewrite Feature - Material Design Icons

### ISSUE THREAD

**Issue by JamesCoyle** [atom-material/atom-material-ui#193]
I recently added support for material design icons to the tool-bar package so that it better blends with this theme. I was thinking it would also be a good idea to add an option to the theme which replaces the default icons with material design icons. What is your opinion on this?

**Comment by der-Daniel** [comment]
I would love it!

**Comment by silvestreh** [comment]
Yes, I always planned to add MD icons. The problem is that they look blurry as hell. Check #82 for more info.

**Comment by der-Daniel** [comment]
How do I override my icons?
I thought this was done by the functionality of the UI theme?

**Comment by JamesCoyle** [comment]
Perhaps a separate package would be the way to go (atom-material-icons)? It would be used to provide material design file icons as well as to replace the icons in the settings panel etc. I'm assuming it would reduce startup time of the atom-material-ui package for those that don't want the icons.

**Comment by silvestreh** [comment]
@JamesCoyle yes, another package would be the best path. There are no official MD icons for file types though. But since the MD guidelines tells us that basically any monochromatic symbol can pass as a MD icon, it wouldn't be difficult to make them.

Or the scope for the icon package could be reduced and only replace those in the settings and tree view (only folders and basic file types like text, images, binaries, compressed files)

**Comment by JamesCoyle** [comment]
Its something that could be added to over time really. The existing file icons packages always seem to look kinda messy IMO as none of the icons are really have the same style. I'd be down for reducing the scope and reusing some icons for similar filetypes would actually fit better with the simplified theme of material design. [This](https://materialdesignicons.com/icon/file-xml) for example could be used for any markup language like HTML, XML, XAML etc.

**Comment by dkerzig** [comment]
They have a nice set of material file icons, unfortunately not for free. But just for reference: http://www.webalys.com/nova/

**Comment by silvestreh** [comment]
@dkerzig Those can't be used. Even if I'd buy a license I wouldn't be able to redistribute them. Besides, Google releases [their icons](https://www.google.com/design/icons/) under CC-By and there's a [big library](https://materialdesignicons.com/) of "unofficial" icons (which, I believe, is related to that icon pack you shared)

**Comment by JamesCoyle** [comment]
I'm pretty busy with uni at the moment but I do mean to give this project a go at some point. I'll be using the official google icons along with those provided by the [material design icons](https://materialdesignicons.com/) project.

**Comment by jerone** [comment]
When implementing, please make this an option, as I've carefully selected my own icons and I don't want being replaced.

**Comment by JamesCoyle** [comment]
It will be a separate icon package as discussed above. As with the `atom-material-syntax` it will be completely optional. :)
