### ISSUE TITLE
Gutter line and editor line gradually get off leveled

### ISSUE THREAD

**Issue by jamby** [atom-material/atom-material-ui#231]
So I noticed this as I was writing some React code, and saw that the deeper I got into my `<div>`'s the more off level both my gutter line and editor line became, and therefore made the cursor and highlight above where it should be (line going into the code instead of under it).

This is what it looks like:

<img width="335" alt="screen shot 2016-02-29 at 3 33 40 pm" src="https://cloud.githubusercontent.com/assets/250728/13408342/553784a0-defb-11e5-9e75-178985537049.png">

**Comment by silvestreh** [comment]
that's weird… which packages are you using?

**Comment by jamby** [comment]
```
Scratchpad@1.0.0
Sublime-Style-Column-Selection@1.5.1
advanced-open-file@0.14.2
aligner@0.19.1
atom-css-comb@3.0.0
atom-fuzzy-grep@0.12.0
atom-material-syntax@0.4.3
atom-material-syntax-dark@0.2.3
atom-material-ui@1.2.0
atom-ternjs@0.13.2
autocomplete-elixir@1.5.13
autocomplete-ruby@0.1.0
autocomplete-sass@0.1.0
blame@0.10.0
block-travel@1.0.4
clean-atom-dark-ui@0.28.0
cucumber@0.5.0
file-icons@1.6.16
gist-it@0.9.0
git-history@3.2.0
highlight-selected@0.11.2
language-babel@2.15.4
language-cjsx@0.3.0
language-diff@0.4.0
language-elixir@0.11.1
language-haml@0.23.15
merge-conflicts@1.3.7
minimap@4.19.0
minimap-find-and-replace@4.4.0
minimap-git-diff@4.1.8
minimap-highlight-selected@4.3.1
package-sync@1.0.0
pigments@0.24.1
pretty-json@0.4.1
project-manager@2.7.6
rails-latest-migration@1.1.6
railscast-theme@0.3.0
remote-edit@1.8.24
seti-syntax@0.4.1
seti-ui@0.9.1
solarized-dark-syntax@1.0.0
toggle-quotes@1.0.0
tree-view-open-files@0.3.0
```

**Comment by jamby** [comment]
By the way, the theme and syntax I'm using are Atom Material UI and Atom Material Syntax Dark (since I am posting it here).

**Comment by silvestreh** [comment]
@jamby it's been a long time, but if you could try Material UI `2.0` on Atom 1.17-beta I'd appreciate it (or … we could just wait a little longer 'til `1.17` hits the stable channel)
