### ISSUE TITLE
Color preferences reset after every update.

### ISSUE THREAD

**Issue by am17torres** [atom-material/atom-material-ui#243]
Pretty simple, I have a custom picked primary and accent color. Every time I do an update to the atom-material-ui package my UI goes back to a blue-green primary and white accent color even though the primary and accent colors show in the setting are what I had selected prior to updating.

**Comment by kxc0re** [comment]
on update the default settings get loaded 
just restarting atom / reloading fixes it ... but maybe we can get a config load after the successful update

Same Problem here on

OS: Win 7 Pro 64bit
version: Atom 1.5.4

**Comment by christoga** [comment]
Install it manually? @am17torres

**Comment by am17torres** [comment]
It's easy enough to correct the problem, I was just adding the issue so it can be tracked.

**Comment by Nikki1993** [comment]
I do not think this is an issue of the package tbh. It most likely has something to do with atom and the way it loads settings. On load values are loaded, but if package is updated it doesn't take into account existing values, thus reload is required.

Imho, this issue should be reported to Atom package management repo (or any other related repo), not material UI as this behavior is not UI related only.

**Comment by silvestreh** [comment]
This happens because your `custom.less` file gets overwritten by the one in the repository. Your settings aren't changed. The next time the theme is loaded it'll overwrite `custom.less` again with your own preferences.

This is a known problem and is the only way to deal with it as long as the guy(s) maintaining [less-cache](https://github.com/atom/less-cache/pull/8) don't update LESS to a more recent version that supports optional imports.

If I had a recent version to work with I could tell LESS to import `custom.less` and not have Atom shit its pants when it doesn't find it. :grin:

**Comment by silvestreh** [comment]
BTW, I added the `wontfix` label… but it's more like a `cantfix`.

**Comment by bbuck** [comment]
Was this a relatively recent change with Atom? I began noticing this issue when the update with improved color selection (for the UI) rolled out -- of course I can't exactly remember which Atom version I had at that time.

**Comment by silvestreh** [comment]
@bbuck this started with the 1.x releases. Color settings are saved as usual, but also written to a `custom.less` file where I override default `less` variables with your custom colors.

This file, `custom.less` is overwritten every time you update the theme. The theme then overwrites it again to use your custom colors after you reload Atom.

**Comment by alexindigo** [comment]
Same here, and it happens pretty often, so it's very annoying.

![Not Purple][http://ia.gs/gXrd/Image%202016-06-25%20at%203.17.50%20PM.png]

**Comment by alexindigo** [comment]
@silvestreh Can you store that data somewhere else? and reread it after update? Maybe localstorage?

**Comment by alexindigo** [comment]
Btw, Atom restart (as suggested above) didn't fix the issue. The only way is to reapply the color selection.

**Comment by willejos** [comment]
restarting atom fixes the issue for me

**Comment by silvestreh** [comment]
Material UI `2.0` is available for Atom 1.17-beta (rewrote the entire thing.) Let me know if this is resolved.

**Comment by am17torres** [comment]
Closing issues I've opened.
