### ISSUE TITLE
Blend tree view with tab bar

### ISSUE THREAD

**Issue by coolhome** [atom-material/atom-material-ui#256]
When the theme setting "Blend tree view with tab bar" is enabled. Toggle Tree View post Atom boot and the blended mode is not added to the UI. (NOTE: Only happens when Tree View is not toggled on boot)

![screen shot 2016-03-21 at 9 12 07 am](https://cloud.githubusercontent.com/assets/700740/13919633/0c34e004-ef45-11e5-8a94-0a4333ec67fe.png)

Possible Solutions: Remove the setTimeout code. Implement a WebKitMutationObserver and listen for when UI panels are pushed to the DOM.

Atom: 1.6.0

Packages
├── Remote-FTP@0.7.20
├── atom-alignment@0.12.1
├── atom-material-syntax@0.4.3
├── atom-material-ui@1.2.9
├── docblockr@0.7.3
├── file-icons@1.6.18
├── highlight-selected@0.11.2
└── minimap@4.21.0

**Comment by silvestreh** [comment]
It works for me even when `tree-view` is disabled and I enable it after Atom booted. Or when I open a new, empty window and add a project folder.

**Comment by coolhome** [comment]
Just did some digging and I have found better reproduction steps. This is a conflict with the Remote-FTP plugin. 

The Remote-FTP -> Settings
 - 'Hide Local When Displayed' unchecked 
 - 'Show View on Startup' checked.

Open new Atom Window.
Add folder to project.
Toggle tree view.

--

Alternative reproduction steps
Packages > tree-view > disable & reenable.

**Comment by silvestreh** [comment]
@coolhome I've followed the alternative reproduction steps (I mentioned it in my previous comment) and didn't get a problem. I'll try the RemoteFTP-related steps.

Also, there IS an observer checking for changes in panels.

**Comment by silvestreh** [comment]
Yeah, no… I just tried the other repro steps and still cannot reproduce it :disappointed:

**Comment by coolhome** [comment]
I couldn't get it to reproduce every time either the more and more I tried to recreate it.

When toggleBlendTreeView was being executed here was the events that happened. I can't remember the exact chain of events but this will get the idea across.

- Adding blending for tree view
- Removed all blending
- Added blending for remote-ftp
