### ISSUE TITLE
Developer Tools Theme

### ISSUE THREAD

**Issue by jerone** [atom-material/atom-material-ui#261]
It is possible to style the Developer Tools too. Would be great to have both (Atom and Dev Tools) in the same (dark) theme.

For inspiration: https://atom.io/packages/dev-tools-themes

**Comment by silvestreh** [comment]
I'm not sure about this. It'd be nice to have, sure, but I really don't think there will be many people going through the hassle of enabling it. If I end up doing it, I would probably make a separate package for it.

**Comment by jerone** [comment]
> ...but I really don't think there will be many people going through the hassle of enabling it.

Only package authors I guess, whom should be familiar with Dev Tools.

> I would probably make a separate package for it

That's perfect too. Then there's Material UI, Material Syntax and Material Dev Tools Theme :+1:

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
