### ISSUE TITLE
git-control package

### ISSUE THREAD

**Issue by lexcast** [atom-material/atom-material-ui#262]
I use [git-control](https://atom.io/packages/git-control) for basic git tasks. Would be nice if it fits with material-ui
![gitcontrol](https://cloud.githubusercontent.com/assets/10590799/14118619/8e9b1b7c-f5a7-11e5-9632-bd3d6344c47b.png)

**Comment by christoga** [comment]
I rather use git-plus than git-control because the commit and the file that used is actually fits in with material-ui

**Comment by zzjin** [comment]
same bother here. Both using git-plus and git-control.

**Comment by christoga** [comment]
You take too long 😂  @zzjin

**Comment by silvestreh** [comment]
@christoga I know… I have a full time job that pays for my bills. I'll get to it eventually.

**Comment by christoga** [comment]
I didn't mean about that, I mean the way he reply bro.
No offense ✌️

**Comment by silvestreh** [comment]
None taken 😄 . I didn't mean to sound harsh, I just wanted to explain the delays.

**Comment by christoga** [comment]
I also have a job dude,
I usually open repo issues when I'm on bed. 😂
