### ISSUE TITLE
Menu bar doesn't get drawn correctly after toggling on and off

### ISSUE THREAD

**Issue by thiagodasilva** [atom-material/atom-material-ui#263]
On linux system, If I set full screen (F11) and then toggle menu bar off and then on again, the menu bar doesn't get drawn correctly until I mouse over.

**Comment by silvestreh** [comment]
Sounds like an issue with your window manager. Please review the CONTRIBUTING.md file and provide some more info :smile:

**Comment by thiagodasilva** [comment]
I'm not able to take a screenshot because as soon as I take the screenshot the bar gets re-drawn.
Atom version: 1.5.4

[thiago@localhost ~]$ uname -a
Linux localhost.localdomain 4.3.4-200.fc22.x86_64 #1 SMP Mon Jan 25 13:37:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[thiago@localhost ~]$ apm list --installed
/home/thiago/.atom/packages (7)
├── atom-material-syntax@0.4.5
├── atom-material-ui@1.2.10
├── autocomplete-python@1.7.2
├── cursor-history@0.5.9
├── git-time-machine@1.3.0
├── markdown-preview-plus@2.3.0
└── vim-mode@0.65.0

**Comment by silvestreh** [comment]
Which flavour of Linux are you using? (Ubuntu/Fedora/Debian/Slackware)

**Comment by thiagodasilva** [comment]
sorry, should have made it more clear. 
4.3.4-200.fc22.x86_6 = Fedora 22

**Comment by silvestreh** [comment]
Oh, right... the `fc22` part… I'll spin a VM and check it out.
