### ISSUE TITLE
Tool Bar and Tool bar main not scaling with theme

### ISSUE THREAD

**Issue by Gunny123** [atom-material/atom-material-ui#266]
Tool bar and tool bar main does not scale with this theme

**Reproduction Steps:**

1. Disable [tool bar](https://atom.io/packages/tool-bar)
and [tool bar main](https://atom.io/packages/tool-bar-main)
2. Enable both packages
3. Set size in px within tool bar to 12px, 24px then 32px
4. Tool bar does not scale to said px

**Expected behavior:**

Tool bar should scale to 32px and/or 24px but instead stops at 16px

**Observed behavior:**

See looped video below

**Screenshots and GIFs**

[Video of issue](https://streamable.com/woi5)

**Atom version:** 1.6.2
**OS and version:** Mac OS X 10.11.4 

**Installed packages:**

├── aligner@0.19.1
├── atom-beautify@0.29.0
├── atom-html-preview@0.1.19
├── atom-jade@0.3.0
├── atom-jshint@2.0.0
├── atom-material-syntax@0.4.5
├── atom-material-syntax-light@0.4.4
├── atom-material-ui@1.2.10
├── autoclose-html@0.23.0
├── chester-atom-syntax@0.1.1
├── color-picker@2.1.1
├── emmet@2.4.3
├── file-icons@1.7.0
├── github-2016-syntax@1.2.0
├── language-javascript-jsx@0.3.7
├── language-swift@0.4.0
├── linter@1.11.4
├── minimap@4.21.0
├── minimap-find-and-replace@4.5.0
├── pigments@0.26.0
├── pinned-tabs@0.2.2
├── tool-bar@0.4.0
├── tool-bar-main@0.0.9
└── xcode-theme@1.4.0

**Additional information:**

* Problem can be reproduced in safe mode: Yes 
* Problem started happening recently, didn't happen in an older version of Atom: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: All

**Comment by silvestreh** [comment]
Hmmm… I still didn't try to reproduce this, but if you're talking about the size settings within the tool-bar package, then the answer is I did an override of those.

**Comment by Gunny123** [comment]
> if you're talking about the size settings within the tool-bar package, then the answer is I did an override of those.

That's exactly what I am talking about lol.

**Comment by silvestreh** [comment]
I'll take another look into restoring those settings because what I did is bullshit. I mean, I don't think it was a good idea, but it worked at the time.

**Comment by Gunny123** [comment]
Much appreciated. I also have another bug I believe I found when setting the override of font size within your settings when setting font size UI

**Comment by silvestreh** [comment]
Yep, it's better to have them in separate issues :+1:

**Comment by Gunny123** [comment]
@silvestreh Thanks for fixing this. Well done!

**Comment by silvestreh** [comment]
@Gunny123 no problem 😄
