### ISSUE TITLE
Selected list item in minimap quick settings looks wrong

### ISSUE THREAD

**Issue by mupchrch** [atom-material/atom-material-ui#270]
The selected list item in the minimap quick settings list is really strange looking.

![image](https://cloud.githubusercontent.com/assets/5797698/14395264/adbe0b46-fd9e-11e5-88f6-c677f9ce0f9a.png)

**Comment by SubhamSatyajeet** [comment]
@silvestreh Thanks for fixing it so quickly. I appreciate it.

**Comment by silvestreh** [comment]
@SubhamSatyajeet no problem. I'll publish an update as soon as I fix a few other bugs 😄
