### ISSUE TITLE
-webkit-font-smoothing override causing unreadable text

### ISSUE THREAD

**Issue by sociallymellow** [atom-material/atom-material-ui#276]
If I get a chance I would love to confirm this myself after digging through the code but just from speculation and a slight amount of research I saw that by default `-webkit-font-smoothing` is set to `subpixel antialiased` but when switching to atom-material-ui theme the sidebar (tree) and tab font weight is thinner and harder to read. I am on a MacBook Pro and have not experienced this previously but did take a month+ long break from Atom so am not sure if this is new or not. The issue is, do other people have this same problem? I added  `* { -webkit-font-smoothing: auto; }` to my styles.less and that fixed it for me but am curious to why this was overridden and if it does appear visually nicer on other systems. Thanks!

**Comment by silvestreh** [comment]
Panels, settings, and tabs are antialiased. You can override this in your user stylesheet with:

```css
atom-panel, .settings-view, .tab-bar {
    -webkit-font-smoothing: inherit;
}
```

I work on a 13" (2011) non-retina MacBook Pro and to me it looks pretty good. I guess it's more of a subjective matter on my part, as I can read both `font-smoothing` modes with no problem.
