### ISSUE TITLE
Tinted tab bar extends past tab bar to toolbar icon

### ISSUE THREAD

**Issue by Gunny123** [atom-material/atom-material-ui#282]
Tint extends to [toolbar](https://atom.io/packages/tool-bar) icon

**Reproduction Steps:**

See video below

**Expected behavior:**

Tint stops at tool bar

**Observed behavior:**

Extends to icon

**Video**

[Video of issue](https://streamable.com/1yzx)

**Atom version:** 1.7.3
**OS and version:** Windows 10

**Installed packages:**

├── aligner@0.22.0
├── atom-beautify@0.29.7
├── atom-html-preview@0.1.19
├── atom-jade@0.3.0
├── atom-material-syntax@0.4.6
├── atom-material-ui@1.2.11
├── chester-atom-syntax@0.1.1
├── color-picker@2.1.1
├── emmet@2.4.3
├── file-icons@1.7.9
├── github-2016-syntax@1.2.0
├── language-javascript-jsx@0.3.7
├── language-swift@0.4.0
├── minimap@4.23.4
├── new-tab@0.5.1
├── pigments@0.26.2
├── pinned-tabs@0.2.2
├── tool-bar@0.4.0
├── tool-bar-main@0.0.9
└── xcode-theme@1.4.0

**Additional information:**

* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: All

I'm guessing this can't be controlled, but I figured I'd mention it.

**Comment by silvestreh** [comment]
Yep, that's the price to pay for restoring `tool-bar`'s size functionality. It will be aligned if you set `tool-bar`'s size to `24px`.
