### ISSUE TITLE
Contrasting Panels Issue and Sugestion

### ISSUE THREAD

**Issue by JamesCoyle** [atom-material/atom-material-ui#283]
Just a small issue really. When the toolbar package is enabled and in a vertical orientation the top icon gets blended with the top bar. That icon doesn't adhere to the contrast panels setting though and remains the darker color even with the setting disabled. Would be nice if this could be fixed.

![image](https://cloud.githubusercontent.com/assets/10384436/15055905/ffa3aa4c-1306-11e6-8be7-8debe7f3e6ec.png)

I was also thinking it would be nice to have more control over the contrasting panels. It would be good to have a control for each individual part so you can darken parts as you prefer. A select box with the options `Normal`, `Dark`, and `Darker` for the treeview, toolbar, editor, settings sidebar, and statusbar would be awesome.

**Comment by silvestreh** [comment]
I'll take a look at the toolbar icon. I agree that it should visually "merge" when the contrast is disabled.

About that feature… I guess you'll have to deal with your user stylesheets for it. I'm not a fan of the idea of having way too many options, I like to keep things simple.
