### ISSUE TITLE
Failed to activate the atom-material-ui theme

### ISSUE THREAD

**Issue by suejon** [atom-material/atom-material-ui#286]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-material-ui](https://github.com/silvestreh/atom-material-ui) package, v1.2.11

### Stack Trace

Failed to activate the atom-material-ui theme

```
At 'styles/vendor/perfect-scrollbar.less' wasn't found in /Users/jonosue/.atom/packages/atom-material-ui/index.less:8:0

LessError: 'styles/vendor/perfect-scrollbar.less' wasn't found
  at /Users/jonosue/.atom/packages/atom-material-ui/index.less:8:0
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.19
pigments, v0.26.2

# Dev
No dev packages
```

**Comment by silvestreh** [comment]
Check if `/Users/jonosue/.atom/packages/atom-material-ui/styles/vendor/perfect-scrollbar.less` file exists. If it doesn't then reinstall the theme.

**Comment by suejon** [comment]
Thanks that sorted it out :)
