### ISSUE TITLE
Can't read selected property name in symbol view

### ISSUE THREAD

**Issue by aopal** [atom-material/atom-material-ui#287]
The highlight showing which object is currently selected seems to be the exact same color as the text color, making it impossible to read the name of the selected object.

Screenshot was taken using atom material syntax theme and the default blue colour scheme of atom material UI.

![test](https://cloud.githubusercontent.com/assets/13202534/15185508/8d45c6fa-1767-11e6-8de7-dbd0eaaa39fb.png)

**Comment by silvestreh** [comment]
And that overlay is provided by which package? Check the CONTRIBUTING file, it'll guide to submit a better bug report.

**Comment by aopal** [comment]
It's the built in atom symbols view

https://atom.io/packages/symbols-view

**Comment by silvestreh** [comment]
I'm not seeing this behavior. Please, check the CONTRIBUTING file.

![captura de pantalla 2016-05-11 a las 17 58 30](https://cloud.githubusercontent.com/assets/1133339/15196305/0d8c0c7c-17a2-11e6-93bb-890cf1114a72.png)
