### ISSUE TITLE
about primary color

### ISSUE THREAD

**Issue by Javacym** [atom-material/atom-material-ui#288]
some text do not show.

**Reproduction Steps:**

1. i set primary color(38,50,56)
![qq 20160521185230](https://cloud.githubusercontent.com/assets/13167757/15447968/3041bff6-1f85-11e6-9550-f3f97703395e.png)

2. but soma text do not show out.
![qq 20160521185405](https://cloud.githubusercontent.com/assets/13167757/15447986/6d386d6a-1f85-11e6-946f-db1e51d7888d.png)
test here:
![qq 20160521185431](https://cloud.githubusercontent.com/assets/13167757/15447992/a4ead23e-1f85-11e6-96db-e932786d6edc.png)

3. how to show in right way?

**Additional information:**

* Problem can be reproduced in safe mode: [No]

**Comment by silvestreh** [comment]
Don't set the primary color to be the same as the background as it is used for text too. If want your tab bar to be the same color as the text editor then just disable the "tinted tab bar" option.
