### ISSUE TITLE
scope name do not show correct.

### ISSUE THREAD

**Issue by Javacym** [atom-material/atom-material-ui#289]
[image]
![qq 20160523075309](https://cloud.githubusercontent.com/assets/13167757/15457407/5a370b86-20bb-11e6-8338-529646f9f88f.png)

.java do not show out ,it is atom bug or material ui bug?

![qq 20160523075528](https://cloud.githubusercontent.com/assets/13167757/15457412/ad389c1e-20bb-11e6-94f6-7750f915e7d2.png)
or show not in a line.

**Comment by silvestreh** [comment]
It's a Material UI bug. I merged a pull request for this very same problem, but it introduced a few other bugs. Anyway, I'll take a look.
