### ISSUE TITLE
Space between icon and filename in tab

### ISSUE THREAD

**Issue by JayXon** [atom-material/atom-material-ui#291]
When I have many tabs open, it's very hard to distinguish between different filenames with same first word. The space between icon and filename is just too much is this case. (And it's not even aligned)

**Reproduction Steps:**

1. open many tabs

**Expected behavior:**

smaller space between icon and filename

**Observed behavior:**

large space

**Screenshots and GIFs**

![screenshot from 2016-05-23 15 24 33](https://cloud.githubusercontent.com/assets/1552641/15486465/e3b087b8-20fa-11e6-9534-aee8c5bd3753.png)

**Atom version:** 1.7.4
**OS and version:** Ubuntu 14.04

**Installed packages:**

├── activate-power-mode@0.5.2
├── atom-beautify@0.29.7
├── atom-material-syntax@0.4.6
├── atom-material-syntax-dark@0.2.5
├── atom-material-ui@1.2.12
├── atom-monokai@0.10.4
├── autocomplete-clang@0.9.3
├── autocomplete-paths@1.0.2
├── autocomplete-python@1.7.3
├── blame@0.10.0
├── clang-format@1.25.0
├── file-icons@1.7.12
├── git-blame@0.4.8
├── git-control@0.7.1
├── git-plus@5.13.5
├── git-time-machine@1.5.2
├── highlight-selected@0.11.2
├── hyperclick@0.0.36
├── language-diff@0.4.0
├── language-log@1.4.0
├── language-proto@0.7.0
├── line-count@0.5.0
├── line-count-status@0.0.3
├── linter@1.11.4
├── linter-clang@3.4.4
├── linter-cppcheck@0.2.0
├── linter-cpplint@1.0.1
├── linter-mixed-indent@1.1.0
├── linter-pylint@1.2.0
├── linter-shellcheck@1.2.0
├── merge-conflicts@1.4.2
├── minimap@4.24.0
├── minimap-find-and-replace@4.5.1
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.4.0
├── minimap-linter@1.1.1
├── seti-syntax@1.0.1
├── seti-ui@1.2.2
├── split-diff@0.8.3
└── you-complete-me@0.7.7

**Additional information:**

* Problem can be reproduced in safe mode: [Yes]
* Problem started happening recently, didn't happen in an older version of Atom: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by silvestreh** [comment]
Alignment is probably due to the package providing the icons. This theme won't change them. The whitespace is according to the Material Design specification (and even then, the white space is not as large as in the spec.)

If you'd like, you can change this in your user stylesheets…

```scss
// File located in ~/.atom/styles.less
.tab-bar .tab .title.icon::before {
    margin-right: 0.25rem;
}
```

That snippet above will reduce icon spacing to 25% of its current value.

**Comment by JayXon** [comment]
Thanks!
