### ISSUE TITLE
Font size on the bottom pane is incorrect

### ISSUE THREAD

**Issue by LinkEscapist** [atom-material/atom-material-ui#292]
font size on the bottom pane is incorrect,this problem is NOT happening with official themes including "One dark"and"Atom Dark" under the same situation,adjust the UI font size in theme config does work to the whole UI but the part i mentioned.

**Expected behavior:**

it should be like the screenshot in the README

**Observed behavior:**

just..that small,the font of directory/CRLF/filetype/encoing on the bottom is so small and nearly unreadable,but for the panes it goes alright.
the following is mine
![myscreenshot](https://cloud.githubusercontent.com/assets/14952800/15612244/8add7046-23f3-11e6-80f1-ce656df250d0.png)
this is the official one,it is obviously bigger and clear
![officialscreenshot](https://cloud.githubusercontent.com/assets/14952800/15612263/a1da2bb8-23f3-11e6-9511-5c094e63f6a9.png)

**Atom version:** 1.7.3
**OS and version:** fedora23，gnome 3 with infinality installed

**Installed packages:**
Community Packages (6) /home/link/.atom/packages
├── atom-material-syntax@0.4.6
├── atom-material-syntax-dark@0.2.5
├── atom-material-ui@1.2.12
├── markdown-preview-plus@2.4.0
├── markdown-preview-plus-opener@0.2.0
└── script@3.7.3

**Additional information:**

* Problem can be reproduced in safe mode: [Yes/No]Yes
* Problem started happening recently, didn't happen in an older version of Atom: [Yes/No] No
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No]Yes

**Comment by silvestreh** [comment]
Not exactly a bug, but the screenshot in the README is outdated. If you want to increase the font-size use this snippet in your user stylesheet:

```css
.theme-atom-material-ui status-bar {
    font-size: 0.75rem;
}
```

Cheers!
