### ISSUE TITLE
Selected tab showing up as solid black bar. Filename illegible.

### ISSUE THREAD

**Issue by superchink** [atom-material/atom-material-ui#295]
The currently selected tab shows up as a solid black bar, and the filename is illegible.

**Reproduction Steps:**

1. Enable Theme
2. Restart (Optional)
3. Observe black bar on selected tab

**Expected behavior:**

Selected tab shows up with the name of the current file.

**Observed behavior:**

Tab shows up as a black bar.

**Screenshots and GIFs**

<img width="379" alt="blacktab" src="https://cloud.githubusercontent.com/assets/91778/15729099/0683dab6-2816-11e6-998e-1e7934a4788a.png">
<img width="1054" alt="blacktab2" src="https://cloud.githubusercontent.com/assets/91778/15729163/8f360dfc-2816-11e6-85d1-75b038d6ec93.png">
![image](https://cloud.githubusercontent.com/assets/91778/15729229/0e35e82a-2817-11e6-9fce-32e58b269d70.png)

**Atom version:** 1.7.4
**OS and version:** OS X 10.11.6 Beta (15G7a)

**Installed packages:**

├── Hydrogen@0.9.1
├── MagicPython@0.5.11
├── Stylus@3.0.0
├── adventurous-syntax@0.2.0
├── atom-beautify@0.29.7
├── atom-cli-diff@1.3.0
├── atom-dark-fusion-syntax@1.1.0
├── atom-html-preview@0.1.19
├── atom-material-syntax@0.4.6
├── atom-material-ui@1.2.13
├── atom-xsltransform@0.8.0
├── auto-detect-indentation@1.0.0
├── autocomplete-python@1.7.3
├── batman-syntax@1.0.1
├── brilliance-white-theme@0.2.1
├── color-picker@2.1.1
├── dash@1.6.1
├── drupal@1.8.0
├── duotone-dark-earth-syntax@1.0.0
├── duotone-dark-forest-syntax@1.0.0
├── duotone-dark-space-syntax@1.0.0
├── duotone-dark-syntax@1.0.0
├── duotone-light-syntax@1.0.0
├── earthsung-by-jackson-syntax@0.3.0
├── editorconfig@1.4.1
├── emmet@2.4.3
├── fizzy@0.16.0
├── genesis-syntax@1.0.7
├── genesis-ui@0.5.0
├── git-plus@5.14.0
├── gruvbox@1.0.5
├── gruvbox-syntax@2.4.1
├── highlight-line@0.11.1
├── hydra-syntax-theme@1.3.0
├── indentation-indicator@0.6.0
├── language-SCSS@0.4.0
├── language-apache@1.5.0
├── language-babel@2.24.4
├── language-gitignore@0.2.0
├── language-hl7@0.1.1
├── language-lua@0.9.4
├── language-python-django-templates@0.1.0
├── language-restructuredtext@0.15.0
├── line-ending-converter@1.3.2
├── linter@1.11.4
├── linter-eslint@7.2.2
├── linter-pep8@1.3.0
├── linter-php@1.2.0
├── linter-scss-lint@3.0.4
├── linter-xmllint@1.3.4
├── markdown-writer@2.3.3
├── meteor-api@2.20.0
├── minimap@4.24.3
├── nucleus-dark-ui@0.8.2
├── pigments@0.29.1
├── project-manager@2.9.7
├── react@0.15.0
├── save-session
├── seti-syntax@1.0.1
├── seti-ui@1.2.3
├── shadow@0.1.0
├── sort-lines@0.14.0
├── tab-control@0.6.9
├── tabs-to-spaces@1.0.2
├── unity-ui@2.1.4
├── url-encode@0.5.0
└── vim-mode@0.65.1

**Additional information:**

* Problem can be reproduced in safe mode: No
* Problem started happening recently, didn't happen in an older version of Atom: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by silvestreh** [comment]
This one is odd… I'll investigate

**Comment by silvestreh** [comment]
Found the culprit! The theme [shadow](https://atom.io/packages/shadow) is overriding stuff. Disabling or uninstalling it should revert things to normal. If you want you can open an issue in their repository.

Cheers!
