### ISSUE TITLE
[Tabs] Drag and Drop Layout

### ISSUE THREAD

**Issue by aitboudad** [atom-material/atom-material-ui#300]
[Drag and Drop Layout Management](https://github.com/atom/tabs/pull/252) has been added recenlty in atom `1.9` but seems not entirely visible with material
see https://github.com/atom/tabs/blob/master/styles/layout.less

**Comment by silvestreh** [comment]
Fixed in a2515c72713a920bcb4e789fd928c85e94ac2ffd 😄
