### ISSUE TITLE
Blend Tree tabBlender missing when install Nuclide

### ISSUE THREAD

**Issue by titanmaru** [atom-material/atom-material-ui#301]
When install Nuclide the tabBlender is not exist even if it is checked.  Will have to go to setting to check and uncheck again to reappear.  I think I already found the problem and fix it.  If you are okay for review I will do a pull request.

**Reproduction Steps:**

1. Install Atom or rm -rf ~/.atom
2. Open Atom and install atom-material-ui and atom-material-syntax
3. Enable color of your choice and enable Blend Tree View
4. Install Nuclide and close atom after finish
5. Reopen Atom

**Expected behavior:**

Blend Tree div which is tabBlender doesn't show up.

**Observed behavior:**

Either Nuclide or Tree-View took longer than expected to appear in DOM so query selector return null or undefined, resulting in toggleBlendTreeView not working as expected

**Screenshots and GIFs**
Before Install Nuclide
<img width="1680" alt="screen shot 2016-06-15 at 11 25 59 pm" src="https://cloud.githubusercontent.com/assets/11767933/16088627/46c300f6-3352-11e6-8e32-a19c022e8a3a.png">
After Install Nuclide
<img width="1680" alt="screen shot 2016-06-15 at 11 27 49 pm" src="https://cloud.githubusercontent.com/assets/11767933/16088630/49eee402-3352-11e6-8ed5-6488e5fd94ee.png">
After deselect and reselect Blend Tree View option
<img width="1680" alt="screen shot 2016-06-15 at 11 40 29 pm" src="https://cloud.githubusercontent.com/assets/11767933/16088706/92c3b69e-3352-11e6-81aa-8fbb190fd435.png">

**Atom version:** 1.8.0
**OS and version:** OS X El Capitan 10.11.5

**Installed packages:**

atom-material-ui
atom-material-syntax
nuclide

**Additional information:**

* Problem can be reproduced in safe mode: No
* Problem started happening recently, didn't happen in an older version of Atom: Yes (I think happen from Nuclide)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects:Yes

**Comment by silvestreh** [comment]
Nuclide's tree view seems to change too often. I don't use it, yet I don't want to screw its users and stop supporting it. I'll see what I can do, but it might take some time, please be patient 😄

**Comment by titanmaru** [comment]
@silvestreh thank you
