### ISSUE TITLE
Numbers Rendering Bug

### ISSUE THREAD

**Issue by paul-siteway** [atom-material/atom-material-ui#302]
OS: macOS Sierra
Atom Version: 1.8.0

![bildschirmfoto 2016-06-15 um 19 37 16](https://cloud.githubusercontent.com/assets/3603487/16090648/b237f426-3330-11e6-86c6-a9be61f42ca8.png)

**Comment by silvestreh** [comment]
what's the font you're using? also, you're using a preview OS

**Comment by paul-siteway** [comment]
Seems to be a global macOS Problem. Just noticed the same in other Apps.

**Comment by silvestreh** [comment]
Alright, feel free to close this issue if you believe it's a problem with the preview release of macOS as I won't install it until a stable release is made.
