### ISSUE TITLE
tree view - current open file

### ISSUE THREAD

**Issue by giolf** [atom-material/atom-material-ui#305]
it's possible to change in the tree view how to show the current open file ?
take the README.md file as example in this picture:
https://i.github-camo.com/545d5462428d9da9c99c1fc0cbd82e47488fd690/687474703a2f2f692e696d6775722e636f6d2f457850596d4a592e706e67

it has a green background color. what i would like to do is to remove that background color and istead of it show a little vertical line on the left with the same color.

**Comment by silvestreh** [comment]
I'm sure you can achieve this using your personal stylesheet located in `~/.atom/styles.less`.
