### ISSUE TITLE
Tab hover tooltip adds line breaks unintuitively

### ISSUE THREAD

**Issue by yannakopoulos** [atom-material/atom-material-ui#307]
When you're editing a file with a long absolute file path, the tab hover tooltip inserts line breaks in unhelpful places. It seems to only break when either the line hits a maximum number of characters or there's a space in the path. The problem with this is that it breaks up individual directory names across lines, which can be hard to read at a glance. Forward slashes seem like a more natural place to break a file path. Maybe these could be added as possible line break locations? Screenshot shows an example of a visually confusing file path tooltip. 

![screenshot from 2016-06-21 14 14 07](https://cloud.githubusercontent.com/assets/9258329/16253358/ffc94ba4-3803-11e6-9d3b-5ef72a68e7c1.png)

**Comment by silvestreh** [comment]
Unfortunately, there is currently no way in CSS to tune line breaking rules by specifying, for example, that a line break is permitted after a certain character wherever it appears in the text.
