### ISSUE TITLE
Legibility with TypeScript when Using Teal Colour

### ISSUE THREAD

**Issue by bennyp123** [atom-material/atom-material-ui#308]
Howdy. Using atom-TypeScript, there are some legibility issues in the status bar down below the pane:

**Screenshots and GIFs**
<img width="818" alt="screen shot 2016-06-25 at 11 24 59 pm" src="https://cloud.githubusercontent.com/assets/1466420/16358960/350cc040-3b2c-11e6-8c04-2240276546f6.png">
<img width="370" alt="screen shot 2016-06-25 at 11 25 12 pm" src="https://cloud.githubusercontent.com/assets/1466420/16358961/37fb6bbc-3b2c-11e6-8ac8-851132e98c5c.png">

**Atom version:** Latest
**OS and version:** El Capitan

**Installed packages:**

Only Good Stuff

**Comment by ruppalsingh** [comment]
+1.

Feel like gouging my eyes out. Love TypeScript, can't stand this.

**Comment by silvestreh** [comment]
Unfortunately I don't use Typescript… could you share a snippet that triggers this behavior so I can take a look?

**Comment by bennyp123** [comment]
Anything which triggers an error ought to do. Create a .ts file in an empty
dir and type in some invalid ts. Simple enough to try and `import {
fake_class } from 'fake`

On Sat, Jul 9, 2016, 9:09 PM Silvestre Herrera <notifications@github.com>
wrote:

> Unfortunately I don't use Typescript… could you share a snippet that
> triggers this behavior so I can take a look?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/atom-material/atom-material-ui/issues/308#issuecomment-231547667>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABZgNHZjEgyu-QL1eaZPyKuU6LGTsDI7ks5qT-PugaJpZM4I-a_2>
> .
>
-- 
Benny Powers
Licensed Israel Tour Guide

In Israel 054-482-5726
In Canada 705-300-0072
In the USA 601-255-3532

bennypowers.com
