### ISSUE TITLE
@input-background-color is white and causes unreadable "light gray on white" text with white @syntax-text-color

### ISSUE THREAD

**Issue by philippu** [atom-material/atom-material-ui#310]
ui-variables.less defines

@text-color: fade(@syntax-text-color, 80%);
@input-background-color: #FFF;

For syntax themes where @syntax-text-color is set to white or light gray, this causes unreadable text in some input boxes. Also, the white background does not match the overall color palette of the UI theme.

**Reproduction Steps:**
N/A

**Expected behavior:**
@input-background-color should probably be some shade of gray like the rest of the theme.

**Observed behavior:**
N/A

**Screenshots and GIFs**
![screen shot 2016-07-25 at 5 30 53 pm](https://cloud.githubusercontent.com/assets/2658619/17122878/352c5822-5294-11e6-9ba2-5e888067a6c1.png)

**Atom version:** 1.8.0
**OS and version:** OS X

**Comment by silvestreh** [comment]
Are you seeing this issue anywhere? Because `@input-background-color` is actually not used anywhere in the theme. It's probably there from the time I rewrote the theme and didn't end up using it.
