### ISSUE TITLE
Failed to activate the atom-material-ui theme

### ISSUE THREAD

**Issue by baiou15** [atom-material/atom-material-ui#311]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-material-ui](https://github.com/silvestreh/atom-material-ui) package, v1.2.13

### Stack Trace

Failed to activate the atom-material-ui theme

```
At 'styles/vendor/perfect-scrollbar.less' wasn't found in /Users/oubai/.atom/packages/atom-material-ui/index.less:8:0

LessError: 'styles/vendor/perfect-scrollbar.less' wasn't found
  at /Users/oubai/.atom/packages/atom-material-ui/index.less:8:0
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  },
  "atom-material-ui": {
    "fonts": {}
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
atom-ternjs, v0.14.2
auto-encoding, v0.5.8
emmet, v2.4.3
file-icons, v1.7.16
markdown-preview-plus, v2.4.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by silvestreh** [comment]
This is an odd one. The `perfect-scrollbar` package isn't used anymore so I removed the offending stylesheet. Please update the theme.
