### ISSUE TITLE
[Question] Where is the setting menu?

### ISSUE THREAD

**Issue by manekinekko** [atom-material/atom-material-ui#312]
![image](https://cloud.githubusercontent.com/assets/1699357/17290494/f982f8ee-57de-11e6-9045-305e23ea5c89.png)

**Comment by silvestreh** [comment]
If you just installed the theme try restarting Atom and let me know if that worked. I usually get the same issue where the settings button isn't there the first time I install the theme.

**Comment by manekinekko** [comment]
I still don't see the cog icon. How would you debug this? I have no errors in the devtools...

**Comment by silvestreh** [comment]
I have no idea how to debug it. But I could use some more info about your system. Check the [CONTRIBUTING](https://github.com/atom-material/atom-material-ui/blob/master/CONTRIBUTING.md) file, it has instructions on how to provide some more info to help me start debugging it 😄

**Comment by manekinekko** [comment]
Alright. I uninstalled all other themes, and re-installed this one. And now I can see the cog button.
I'm closing this issue.
Thanks for your help ^^
