### ISSUE TITLE
Shadow effect on Tool-bar package

### ISSUE THREAD

**Issue by Gunny123** [atom-material/atom-material-ui#314]
Weird shadowing at bottom of the toolbar
**Reproduction Steps:**

1. Launch Atom 
2. Ensure tool-bar is activated

**Expected behavior:**

Solid uniform color

**Observed behavior:**

Shadow at bottom. See this [screenshot](http://imgur.com/iABAwT1) at look at bottom right

**Screenshots and GIFs**

[Shadow effect at bottom right](http://imgur.com/iABAwT1)

**Atom version:** v1.9.2
**OS and version:** Windows 10 Home Anniversary Update

**Installed packages:**

├── aligner@0.22.1
├── atom-beautify@0.29.10
├── atom-html-preview@0.1.22
├── atom-jade@0.3.0
├── atom-material-syntax@0.4.6
├── atom-material-syntax-light@0.4.5
├── atom-material-ui@1.3.3
├── color-picker@2.2.2
├── emmet@2.4.3
├── file-icons@1.7.17
├── github-2016-syntax@1.2.0
├── gl-light-syntax@2.2.0
├── improved-chester-atom-syntax@0.2.0
├── language-javascript-jsx@0.3.7
├── language-swift@0.4.0
├── language-vue@0.14.1
├── minimap@4.24.7
├── new-tab@0.5.1
├── php-cs-fixer@2.5.9
├── pigments@0.31.2
├── pinned-tabs@0.3.1
├── tool-bar@1.0.0
├── tool-bar-main@0.0.9
├── two-light-ui@1.1.0
├── wwdc16-syntax@1.0.0
└── xcode-theme@1.4.0

**Additional information:**

* Problem can be reproduced in safe mode: Y
* Problem started happening recently, didn't happen in an older version of Atom: Y
* Problem can be reliably reproduced, doesn't happen randomly: Y
* Problem happens with all files and projects, not only some files or projects: Y

**Comment by silvestreh** [comment]
Not related to Material UI. This happens when the `tool-bar` is scrollable, might b a bug with the `tool-bar` package.
