### ISSUE TITLE
Cannot see settings gear.

### ISSUE THREAD

**Issue by scrawfor** [atom-material/atom-material-ui#316]
I cannot see the settings gear on one of my machines.  Clicking the name of the theme takes me to a display with some of the settings, but none of these seem to have any affect.  This only affects my Linux VM.  My windows machines seem unaffected.

**Screenshots and GIFs**

![image](https://cloud.githubusercontent.com/assets/7061689/17464937/ce719df8-5cb7-11e6-8200-d33c10c50b8a.png)
![image](https://cloud.githubusercontent.com/assets/7061689/17464967/7d0f4194-5cb8-11e6-8de2-0c771dcd1bee.png)

**Atom version:** 1.9.4 - 1.9.6
**OS and version:** Fedora 24 - Up to date.

**Installed packages:**

atom-material-ui, atom-material-syntax

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Atom: Haven't used it enough.
- Problem can be reliably reproduced, doesn't happen randomly: Yes - every boot.
- Problem happens with all files and projects, not only some files or projects: Yes

**Comment by silvestreh** [comment]
Sorry it took this long, but it sounds like an issue with `settings-view`.
