### ISSUE TITLE
Git file highlighting in atom 1.10 beta

### ISSUE THREAD

**Issue by Klathmon** [atom-material/atom-material-ui#317]
In 1.10 beta (started at beta2 IIRC and is still an issue in 1.10.0-beta5) the git highlighting for the files in the tree view is messed up.

If any file changes, it highlights all files to be that color all the way up to the root folder.

This only happens if the Atom Material UI theme is active.

**Screenshots and GIFs**
In this example, the only file added is src/components/scanner/index.js
![image](https://cloud.githubusercontent.com/assets/1879551/17627557/a873e2ac-607f-11e6-9944-b91c802f609f.png)

In this one the only file changed is src/components/cacheNotifier.jsx
![image](https://cloud.githubusercontent.com/assets/1879551/17627657/032fd782-6080-11e6-8cc3-0ac632f7b22c.png)

**Atom version:** 1.10.0-beta5
**OS and version:** Windows 10 Pro Version 10.0.14393 Build 14393

**Additional information:**

* Problem can be reproduced in safe mode: No (since the theme can't be activated)
* Problem started happening recently, didn't happen in an older version of Atom: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes ( I tried it in 2 separate projects)

**Installed packages:**

I've got a lot of crap to clean out of here, but this is the current list:

```
atom-beautify
atom-format-lua
atomic-chrome
atom-material-syntax
atom-material-syntax-light
atom-material-ui
atom-ternjs
atom-ungit
autocomplete-modules
autocomplete-sass
compare-files
devdocs
docblockr
editor-stats
file-icons
file-types
git-control
git-history
git-log
git-plus
git-time-machine
glowing-cursor
gulp-control
highlight-selected
language-babel
language-cuda
language-dotenv
language-generic-config
language-lua
language-nginx
language-powershell
language-rust
language-smarty-php
less-than-slash
linter
linter-coffeelint
linter-csslint
linter-js-standard
linter-lua
linter-php
linter-scss-lint
local-history
markdown-pdf
markdown-preview-plus
merge-conflicts
minimap
minimap-highlight-selected
minimap-pigments
neon-syntax
pigments
project-manager
Remote-FTP
source-preview
standard-formatter
Sublime-Style-Column-Selection
sync-settings
tab-title
travis-ci-status
uglify
```

**Comment by tikiatua** [comment]
Same issue on OS X El Capitan

**Comment by octoxan** [comment]
Same issue on Windows 10.

**Comment by silvestreh** [comment]
Yep, I can confirm too. Unfortunately I've got no time to hack on this. Contributions are very much welcomed!

**Comment by octoxan** [comment]
I'll look into it tomorrow morning and see if I can help

**Comment by Kampfmoehre** [comment]
Got the same problem on Debian for a while now. I build Atom directly from master once a week or so.

**Comment by silvestreh** [comment]
OK… this is weird. I commented out all styles with VCS coloring and I'm still getting the problematic tree-view 😕  … I'll keep investigating, if anyone can shed some light I'd really appreciate it.
