### ISSUE TITLE
atom-pane-resize-handle changes

### ISSUE THREAD

**Issue by simurai** [atom-material/atom-material-ui#323]
Once https://github.com/atom/atom/pull/12300 merges, the vertical `atom-pane-resize-handle` can't be used to drag the panes anymore. I think the problem is:

1. In Core, the `:before` pseudo element [is now used](https://github.com/atom/atom/pull/12300/commits/ee0a03b0b212b05f01dc76e3ecb0b5889b4cc90b) for the handle because [Chromium 52 will change some flexbox behaviour](https://developers.google.com/web/updates/2016/06/absolute-positioned-children?hl=en).
2. This theme uses the `::before` already, but then removes it again [here](https://github.com/atom-material/atom-material-ui/blob/master/styles/panes.less#L26). Which makes it un-clickable/draggable.

- Also, I think the `height: 50%;` for [::after](https://github.com/atom-material/atom-material-ui/blob/master/styles/panes.less#L36) doesn't work anymore because the parent elements has now 0 height.
- Plus the `atom-pane-resize-handle.horizontal` are now much wider.

**Reproduction Steps:**

1. Build Atom with the `tj-upgrade-electron` branch. 
2. Split a second pane down (so that there is a `atom-pane-resize-handle.vertical`) 
3. Try to resize the panes

**Expected behavior:**

Panes should get resized

**Observed behavior:**

Resize cursor doesn't show up, panes can't be resized.

**Screenshots and GIFs**

![handle](https://cloud.githubusercontent.com/assets/378023/18024850/d5e47e32-6c4f-11e6-97f9-a7eef3616fc2.gif)

**Atom version:** `1.11.0-dev-2d97d18`
**OS and version:** macOS `10.11.6`

**Additional information:**

* Problem can be reproduced in safe mode: No
* Problem started happening recently, didn't happen in an older version of Atom: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by simurai** [comment]
Not sure if you have built Atom before, so you can test the changes in Core. Let me know if not.

The line made with `::before` might can get replaced with a border?

**Comment by silvestreh** [comment]
Hey @simurai! I tried using a border before but results weren't great to say the least:

![captura de pantalla 2016-08-27 a las 1 09 24 p m](https://cloud.githubusercontent.com/assets/1133339/18028543/ff8119fa-6c57-11e6-8038-3cf6f87f56b2.png)

It overlaps with the scrollbar 😞 

But fear not, I can also use the `::after` pseudo element to achieve the same results.
