### ISSUE TITLE
Timecop view seems to be styled incorrectly

### ISSUE THREAD

**Issue by Alaneor** [atom-material/atom-material-ui#326]
Opening the Timecop view, I noticed that the view is most likely not styled as intended. Attaching screenshot.

**Reproduction Steps:**
1. Open Atom 1.10.2
2. Open Timecop view (_Packages -> TImecop -> Show_)
3. Behold, and despair

**Expected behavior:**

Peaceful thoughts while inspecting my packages' load times

![screen shot 2016-09-09 at 09 51 33](https://cloud.githubusercontent.com/assets/3058150/18379466/09f942c0-7673-11e6-9fe2-8e8641dabc4d.png)

**Atom version:** 1.10.2
**OS and version:** macOS 10.11.6

**Installed packages:**

```
├── Stylus@3.0.0
├── activate-power-mode@0.8.1
├── api-blueprint-preview@0.7.0
├── atom-beautify@0.29.11
├── atom-chai-snippets@0.3.0
├── atom-material-syntax@0.4.6
├── atom-material-syntax-light@0.4.5
├── atom-material-ui@1.3.6
├── atom-pair@2.0.10
├── atom-ternjs@0.15.0
├── atomatigit@1.5.5
├── autocomplete-go@1.1.1
├── autocomplete-modules@1.6.1
├── build@0.65.0
├── builder-go@1.0.1
├── busy@0.6.0
├── docblockr@0.8.5
├── editorconfig@1.4.1
├── environment@1.2.0
├── file-icons@1.7.19
├── git-history@3.2.0
├── git-plus@5.16.2
├── git-projects@1.17.0
├── git-time-machine@1.5.3
├── go-config@1.2.3
├── go-debug@0.1.22
├── go-get@1.0.4
├── go-plus@4.2.0
├── godoc@0.4.0
├── gofmt@1.1.8
├── gometalinter-linter@1.1.1
├── gorename@1.0.3
├── gruvbox-plus-syntax@1.2.5
├── highlight-selected@0.11.2
├── indent-guide-improved@1.4.10
├── language-api-blueprint@1.0.2
├── language-babel@2.37.0
├── language-diff@0.4.0
├── language-docker@1.1.7
├── language-dotenv@1.0.0
├── language-gitignore@0.2.0
├── language-ini@1.16.0
├── language-jade@0.7.1
├── language-mjml@1.3.0
├── language-swift@0.4.0
├── lcov-info@0.12.0
├── linter@1.11.16
├── linter-docker@0.1.2
├── linter-eslint@7.3.0
├── linter-js-yaml@1.2.5
├── linter-jsonlint@1.3.0
├── linter-package-json-validator@1.0.1
├── merge-conflicts@1.4.4
├── minimap@4.25.0
├── minimap-git-diff@4.3.1
├── navigator-godef@1.0.4
├── node-debugger@1.7.0
├── set-syntax@0.3.0
├── sort-lines@0.14.0
├── standardjs-snippets@2.4.0
├── sync-settings@0.7.2
├── terminal-plus@0.14.5
├── tester-go@1.0.6
└── todo-show@1.7.0
```

**Comment by silvestreh** [comment]
Yep, it looks hideous indeed. I'll take a look at it. Thanks!

**Comment by silvestreh** [comment]
BTW, you're using a different font for the UI, right?

**Comment by Alaneor** [comment]
Yes, I have overridden the font everywhere to be Operator Mono.

Thanks for looking into it!

**Comment by trunneml** [comment]
Same here. With a light color theme it is unreadable.
![2016-09-17](https://cloud.githubusercontent.com/assets/241487/18610054/fa156104-7d11-11e6-98b6-7c1cd7ee12c7.png)
![minibar](https://cloud.githubusercontent.com/assets/241487/18610053/fa15277a-7d11-11e6-8309-a8a39248419c.png)
