### ISSUE TITLE
Compact Project Find Result

### ISSUE THREAD

**Issue by zhaocai** [atom-material/atom-material-ui#327]
Is there a way to make the **project find result** compact?

As shown in the screenshot below, the margin between lines is too large.

**Reproduction Steps:**

search with project-find

**Screenshots and GIFs**

![project find result](https://dl.dropboxusercontent.com/u/1897501/Screenshots/atom-material-search-result-compact.png)

**Atom version:** 1.10.2
**OS and version:** Windows 10

**Comment by ashtonmeuser** [comment]
👍

**Comment by silvestreh** [comment]
Should be better in Material UI 2.0.

<img width="1160" alt="captura de pantalla 2017-05-04 a la s 16 23 24" src="https://cloud.githubusercontent.com/assets/1133339/25721211/068e6ac4-30e6-11e7-9966-b53ee414089a.png">
