### ISSUE TITLE
Headline in Project Search and Replace has styling problems

### ISSUE THREAD

**Issue by trunneml** [atom-material/atom-material-ui#328]
The headline in the project search has some styling problems. (Like Timecop and the Minimap).

**Reproduction Steps:**
1. Use a light syntax theme
2. Find -> Find in Project (Ctrl + Shift + F)
3. Look at the headline

**Expected behavior:**

Correctly styled headline with correct background color and font size.

**Observed behavior:**

Black-font on dark grey background 
**Screenshots and GIFs**

![2016-09-18 1](https://cloud.githubusercontent.com/assets/241487/18614385/cac67574-7d8d-11e6-8aad-1b3b9bb0126e.png)

**Atom version:** 1.10
**OS and version:** Windows 10 Pro x64

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]
- Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by r0ckarong** [comment]
Got the same problem. I use the pen-paper-coffee syntax and just worked around it for now by adding the property to my stylesheet with the gutter color of the active syntax.

```
.preview-pane .panel-heading
{
  background-color: #e0dad3;
}
```

@trunneml This happens on macOS and Ubuntu as well. Not platform specific it's a styling issue with the theme.
