### ISSUE TITLE
panel coloring is broken

### ISSUE THREAD

**Issue by go2sh** [atom-material/atom-material-ui#329]
.panel-heading and .inset-pading looks awkward in some cases. The build-tools package e.g. falls back to default colors from atom. Also the intended look for the .inset-pading is not visible.

This comes many from the panels.less file, which isn't overwriting the defaults properly.

**Expected behavior:**
 See colors from the material design.

**Observed behavior:**
 See colors from the core atom style

**Atom version:** 1.10.2
**OS and version:** Windows 7

**Comment by silvestreh** [comment]
could you please share a screenshot so I can see what you mean? 😄

**Comment by go2sh** [comment]
UI with material theme:
![image](https://cloud.githubusercontent.com/assets/150886/20663707/c14122ee-b558-11e6-95e5-64e0241ab7d0.png)

UI with One light:
![image](https://cloud.githubusercontent.com/assets/150886/20663655/9b97135a-b558-11e6-8f13-3f7b349069c2.png)

The headings linke "General" and "Highlighting" and those "Modifiers:" stuff with the slider. In all other themes the look is more or less consistent.

**Comment by silvestreh** [comment]
This is likely been fixed in Material UI `2.0`. Would love if you could try it out! (It's for Atom 1.17, so you'll need to install Atom-beta)
