### ISSUE TITLE
Theme no longer uses color from Setting as Primary color

### ISSUE THREAD

**Issue by smlombardi** [atom-material/atom-material-ui#330]
Primary color is set to be "Blue Grey Primary", but the theme is using Green. It was working before I updated to Sierra, although on another mac it worked fine on Sierra.

![screen shot 2016-09-26 at 8 36 47 am](https://cloud.githubusercontent.com/assets/835148/18834513/62491c44-83c4-11e6-8da2-e280c6b2a3c6.jpg)

Atom 1.11.0-beta5, macos10.12 (16A323), atom-material-ui 1.3.6

**Comment by smlombardi** [comment]
Seems that closing an re-opening the project restored the correct color (I earlier tried just quitting and restarting Atom, which did not).

**Comment by seminull** [comment]
I had this issue, turned out that portions of my .atom in home were owned by root.  Presumably because I ran a `sudo apm update`.  Hopefully this helps someone else.

**Comment by silvestreh** [comment]
Yep, losing write access to `~./atom` could break things. The custom color feature works by overwriting a LESS file where color variables are defined and then reloads the theme.
