### ISSUE TITLE
Notification text wraps prematurely

### ISSUE THREAD

**Issue by zmb3** [atom-material/atom-material-ui#331]
It seems that the text in Atom notifications is wrapping prematurely.

In this particular case, I have two notifications stacked on top of eachother, and the notification on the bottom is exhibiting the problem.  If I clear the topmost notification so that there is only one notification remaining, the layout corrects itself.

**Reproduction Steps:**

This is easy to reproduce with the Go-Plus package, but requires a bit of setup if you're not a Go developer.  I'm happy to share my screen and show a repro.
1. Install Go toolchain and set `$GOPATH`
2. Launch Atom
3. Invoke the `golang: update packages` command and observe the notifications

**Expected behavior:**

Text wraps only after using all available horizontal space.

**Observed behavior:**

Text only fills about 50% of the horizontal space and then wraps.

**Screenshots and GIFs**

Lower notification text wrapping:
![image](https://cloud.githubusercontent.com/assets/7527103/18898156/0ba62b1e-84ed-11e6-8860-5d988225312f.png)

Dev tools view:
![image](https://cloud.githubusercontent.com/assets/7527103/18898048/33c162fe-84ec-11e6-9c7d-f79ef15729b7.png)

After dismissing the upper notification the layout corrects itself:
![image](https://cloud.githubusercontent.com/assets/7527103/18898188/323552fa-84ed-11e6-98d1-7f428a0d23ba.png)

**Atom version:** 1.11.0-beta5
**OS and version:** macOS Sierra

**Installed packages:**

atom-material-syntax@0.4.6
atom-material-ui@1.3.6
atom-pair@2.0.10
autocomplete-go@1.2.0
builder-go@1.0.1
git-plus@5.17.1
go-add-tags@0.0.0
go-config@1.2.4
go-debug@0.1.22
go-get@2.0.0
go-hyperclick@1.1.0
go-plus@4.2.0
godoc@1.0.0
gofmt@1.2.0
gometalinter-linter@1.2.1
gorename@1.1.0
hyperclick@0.0.38
linter@1.11.16
linter-eslint@7.3.2
linter-js-standard@3.4.1
linter-js-standard-jsx@4.1.2
material-syntax@0.5.0
navigator-godef@1.1.0
react@0.16.0
tester-go@1.1.0

**Additional information:**
- Problem can be reproduced in safe mode: [Yes/No]
- Problem started happening recently, didn't happen in an older version of Atom: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]
- Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by silvestreh** [comment]
I can't seem to reproduce this. Could you take a screenshot of the markup rendered by Chromium? Open Atom's DevTools and take a screenshot of the HTML.

**Comment by zmb3** [comment]
Does this help?

![image](https://cloud.githubusercontent.com/assets/7527103/20650806/642c713e-b4a5-11e6-87ce-ead855267b9c.png)

**Comment by silvestreh** [comment]
it sure does. now I can simulate those notifications manually. thanks!

**Comment by silvestreh** [comment]
Ok, looks like I managed to reproduce and fix this. Here's what it should look like now:

![captura de pantalla 2016-11-27 a las 5 17 22 p m](https://cloud.githubusercontent.com/assets/1133339/20651498/535f2b9c-b4c5-11e6-967a-24ccea23d72a.png)

I'll publish a new patch so you can test it 😄

**Comment by silvestreh** [comment]
Should be fixed in `1.3.8` which I just pushed to APM. Thanks for your help! 😄

**Comment by zmb3** [comment]
Yep, the fix looks great.  Thanks!
