### ISSUE TITLE
Tabs doesn't scale when tab-bar is full

### ISSUE THREAD

**Issue by The-Pingu** [atom-material/atom-material-ui#333]
Technical description: Tabs doesn't decrease in width beneath a certain value.
General description: When the tab-bar is full of tabs, opening a new tab doesn't resize the other tabs in width. Instead it moves the new tab out of the window and it's therefore unable to choose (click).

Reproduction Steps:
1. Open Atom
2. Keep going opening tabs (CTRL+N) until you notice the behavior

Expected behavior:
Tabs should scale correctly in size.

Observed behavior:
Tabs doesn't scale as expected. Making it impossible to select the newest tabs.

Atom version: 1.10.2
Package version: 1.3.6
OS and version: Ubuntu 15.10

**Comment by silvestreh** [comment]
You can either scroll the tab bar horizontally or get into the theme's settings and override this behavior by enabling the `No minimum width for tabs` option.
