### ISSUE TITLE
Color new Mac custom title-bar to match tab bar color

### ISSUE THREAD

**Issue by abraham** [atom-material/atom-material-ui#334]
Atom 1.11.0 shipped with a new [custom title-bar API](https://github.com/atom/atom/pull/11790) that can be themed. It would be great if that matched the primary color when "tinted tab bar" is enabled.

**Screenshots and GIFs**

![This is the titlebar provided by one-dark-ui, with the oceanic-next syntax](https://cloud.githubusercontent.com/assets/170500/15407534/ad8b0c4a-1e0b-11e6-842e-de6df82d5e15.png)

**Atom version:** 1.11.0
**OS and version:** macOS

**Comment by silvestreh** [comment]
This is already implemented in 1834afa52c87f54e447c4926edbac929f5e401ed 😄  …

**Comment by abraham** [comment]
Is there anything I have to do to make it work? It's just the default gray title-bar for me.

**Comment by abraham** [comment]
🤓 🌴 totally missed that I have to enable this in Atom. I had assumed that it would just work.

**Comment by silvestreh** [comment]
Oh yeah… You need to enable that in Atom's Core Settings… for future reference:

![captura de pantalla 2016-10-12 a las 5 21 17 p m](https://cloud.githubusercontent.com/assets/1133339/19326313/64438cbc-90a0-11e6-9956-44df5752cd6d.png)

Enable `Use Custom Titlebar`.

**Comment by sn0wyfall** [comment]
@silvestreh Thank you! Which theme is that?

**Comment by silvestreh** [comment]
@sn0wyfall It's [`atom-material-ui`](https://atom.io/packages/atom-material-ui) 😄

**Comment by sn0wyfall** [comment]
@silvestreh Oh, okay! Did you make it purple manually? Just asking because it looks nice :)

**Comment by silvestreh** [comment]
@sn0wyfall yup, it's within the theme's settings. There are color pickers to pick whatever color you like and there's a `<select>` with some presets (I'm using the purple preset)

**Comment by sn0wyfall** [comment]
@silvestreh Thanks for the tip! :)

**Comment by DhruvSiri** [comment]
@sivestreh I have both the ui and syntax theme but when i enable the syntax the custom header color turns to turqouise and i can't change it. What shud I do?

**Comment by DhruvSiri** [comment]
nvm i solved it

**Comment by silvestreh** [comment]
@DhruvSiri good to know. The theme is largely unmaintained because I switched text editors. Also, not exactly sure what's going to happen with Atom since Microsoft acquired GitHub a while back and they already have VSCode. 🤷🏽‍♂️
