### ISSUE TITLE
atom-toolbar not styled correctly

### ISSUE THREAD

**Issue by jimmyff** [atom-material/atom-material-ui#339]
Buttons are incorrectly styled and you can't see the options in drop down menus.

**Comment by silvestreh** [comment]
Care to share a screenshot or reproduction steps?

**Comment by jimmyff** [comment]
![screen shot 2016-11-30 at 13 07 26](https://cloud.githubusercontent.com/assets/298850/20753425/38ed1e28-b6fe-11e6-9395-88a59f69539e.png)

The toolbar is above the file tabs, as you can see the buttons are not themed and the select menu has strange styling.

You can test yourself by installing the 'dartlang' package will install and configure the 'atom-toolbar' package.

**Comment by silvestreh** [comment]
Cool thanks! I'll take a look and fix this ASAP 😄

**Comment by jimmyff** [comment]
Will you accept a pull request if I fix it?

**Comment by silvestreh** [comment]
Absolutely! As I mentioned in other issues, I'm focusing on the 2.0 branch for now. I'll release it alongside Atom 1.17

**Comment by jimmyff** [comment]
Ah, didn't realise you were working on an entirely new version. I'll just use a different theme until the 2.0 version lands along with Atom 1.17!
