### ISSUE TITLE
<small> tag not styled correctly with atom/markdown-preview

### ISSUE THREAD

**Issue by tsaiid** [atom-material/atom-material-ui#340]
<small> tag not styled correctly with [atom/markdown-preview]

**Reproduction Steps:**

1. type sample text: ```text <small>text</small>```
2. set theme to Atom Material
3. toggle markdown preview

**Expected behavior:**

The text in small tag should be smaller then normal text.

**Observed behavior:**

The text in small tag larger then normal text.

**Screenshots and GIFs**

![2016-11-02 1 28 59](https://cloud.githubusercontent.com/assets/4302689/19917741/e03ac19e-a100-11e6-9488-d93601c4ad82.png)    
^ error style with atom-material-ui theme

![2016-11-02 1 28 31](https://cloud.githubusercontent.com/assets/4302689/19917753/fad14d16-a100-11e6-8520-ef30e6066158.png)    
^ correct style with atom dark theme

**Atom version:** 1.11.2
**OS and version:** macOS Sierra 10.12.1

**Installed packages:**

Community Packages (6) 
├── atom-beautify@0.29.13
├── atom-material-syntax@0.4.6
├── atom-material-ui@1.3.6
├── language-markdown@0.17.0
├── markdown-scroll-sync@2.1.2
└── markdown-table-formatter@2.8.3

**Comment by silvestreh** [comment]
Fixed in #341
