### ISSUE TITLE
Display Issue (Bad Colour Choice) for Restart Notification

### ISSUE THREAD

**Issue by pingshunhuangalex** [atom-material/atom-material-ui#342]
With the latest Atom version 1.12.2 and Atom Material (Dark), the following issue remains...

It happens when the below notification is triggered (after updating packages that require restart). It's just a bad choice of color which makes it almost impossible to see the restart text on the button both before and after the clicking.

![a6b806b2-a8d9-11e6-8765-e347948d9fe5](https://cloud.githubusercontent.com/assets/17170199/20235499/8b0c2282-a8e7-11e6-8e61-75c94b229e69.png)

Hope it can be fixed soon. Thanks.

**Comment by Spidersouris** [comment]
Can confirm.

![Screenshot](https://puu.sh/sfU90/097347155a.png)
