### ISSUE TITLE
Breaks Platformio Serial Monitor Prompt

### ISSUE THREAD

**Issue by sdaitzman** [atom-material/atom-material-ui#344]
[Short description of problem here]
See https://github.com/platformio/platformio-atom-ide/issues/186
**Reproduction Steps:**

1. Have Platformio and atom-material-ui installed
2. Try to raise Serial Monitor on a display that isn't massive
3. Show advanced settings

**Expected behavior:**

All dropdowns are a reasonable size, or at least visible or scrollable

**Screenshots and GIFs**

See https://github.com/platformio/platformio-atom-ide/issues/186

See https://github.com/platformio/platformio-atom-ide/issues/186

**Installed packages:**

Relevant packages listed at https://github.com/platformio/platformio-atom-ide/issues/186

**Comment by sdaitzman** [comment]
I'm mostly just creating this issue because I'm not sure which package needs to fix the issue, and I want a link between any thinking taking place here on the issue and any thinking taking place at platformio on the issue

**Comment by silvestreh** [comment]
This packages needs fixing. Mostly due to poor decision making when starting from scratch with 1.0.0 – sorry! 😅 

I'm doing a ___HUGE___ refactor which will eventually become 2.0 and (hopefully) be more compatible with other packages and won't need so much tweaking in a per-package basis.

**Comment by sdaitzman** [comment]
Got it! Is there an issue I should tag to associate that project with this issue so it can be closed then?
