### ISSUE TITLE
Can't select the theme in Atom

### ISSUE THREAD

**Issue by hiiiPipe** [atom-material/atom-material-ui#345]
When I go to the drop down menu UI and Syntax Theme,  both material-ui and material-syntax don't show up, even though they're both installed.

![slika1](https://cloud.githubusercontent.com/assets/22946559/21297007/2c995032-c578-11e6-9935-18a235a4ffb9.png)
![slika2](https://cloud.githubusercontent.com/assets/22946559/21297010/33122bd2-c578-11e6-9fbe-376400ba38ab.png)

**Comment by silvestreh** [comment]
I can see both options in your screenshot. "Atom Material"
