### ISSUE TITLE
Material-Ui's Big Button Covers Part of the Text in Merge Conflicts

### ISSUE THREAD

**Issue by pingshunhuangalex** [atom-material/atom-material-ui#351]
Honestly, I'm not sure who I should turn to regarding this issue. Since `Atom Merge Conflicts` hasn't been updated for ages, I thought I may have a better shot here.

I'm using material-ui and material dark syntax, and material-ui uses a larger button compared to other themes. This looks great, but it introduces a problem when using `Atom Merge Conflicts`. The first line of the conflicts will be entirely covered due to the size of the button elements. Just wonder if there is any chance this theme can use a smaller button like those in the defaults, or if the developer can find some kind of a workaround. (The issue is also raised here: https://github.com/smashwilson/merge-conflicts/issues/250) Thanks.

![image](https://cloud.githubusercontent.com/assets/17170199/22540711/da2e6dce-e975-11e6-9916-cd3055b423a6.png)

**Comment by pingshunhuangalex** [comment]
Hi @silvestreh 
Just wonder if there is any plan on getting this issue fixed as `Merge Conflicts` is a big plus for atom itself. Thanks.

**Comment by silvestreh** [comment]
Yeah, I'm working on a major refactor which will, hopefully, make the theme "more compatible" with other packages.

**Comment by pingshunhuangalex** [comment]
Hi @silvestreh 
Instead of opening new issues, just want to list some other colouring issues I noticed recently. They are all error/warning shown in lintering. Hope they will all be fixed in the coming major refactor. Thanks.

Inline Warning Text for Flake8:
![image](https://cloud.githubusercontent.com/assets/17170199/22813422/9ccdbf36-ef9f-11e6-94bc-d40a5c6e17ff.png)

Error Panel Error Type for Eslint when Hovered Over:
![image](https://cloud.githubusercontent.com/assets/17170199/22813484/01b73422-efa0-11e6-8bdd-801c3c006c42.png)

**Comment by Arcanemagus** [comment]
That is actually a Linter issue (https://github.com/steelbrain/linter/issues/1317), the text color was being forced to `white` instead of using a theme variable.

**Comment by pingshunhuangalex** [comment]
Thanks @Arcanemagus for the support on the Linter issue.
I guess people just read reported issues too quickly, and sometimes it's just really hard to say whether the background colour or the text colour should be changed, especially when they are maintained by two different developers.
