### ISSUE TITLE
Panel shading inconsistent

### ISSUE THREAD

**Issue by jstocksix** [atom-material/atom-material-ui#353]
Unsure if bug or I need to add some custom styling, although this issue only apparent with the material-ui and material-syntax packages (which I love, but this issue is distracting). 

Thanks so much for the work so far though!

**Reproduction Steps:**

Any text file.

**Expected behaviour:**

Consistent shading across panel regardless of line length or position of cursor.

**Observed behavior:**

Shading appears to be padded around longer lines of text, and follows the position of the cursor (line is highlighted) as well. Padding appears to be 6 lines 'long'.

**Screenshots and GIFs**

![screen shot 2017-02-10 at 11 59 07](https://cloud.githubusercontent.com/assets/18112875/22809866/3864ed50-ef89-11e6-9c39-a5bd9aca2758.png)

![screen shot 2017-02-10 at 11 57 16](https://cloud.githubusercontent.com/assets/18112875/22809888/514ad73a-ef89-11e6-987f-881d40191dd4.png)

**Atom version:** 1.14.1
**OS and version:** macOS Sierra

**Comment by silvestreh** [comment]
This is not an issue with the theme, but with Electron itself. Check #335 for further info 👍

**Comment by jstocksix** [comment]
Ahh yep, that makes sense. I did think it might have been something further upstream than material-ui... Thanks for the link and thanks for your great work!
