### ISSUE TITLE
Tooltip animation interferes with mouse hover events.

### ISSUE THREAD

**Issue by dantarion** [atom-material/atom-material-ui#355]
https://github.com/platformio/platformio-atom-ide-terminal/issues/149

Basically, when the tooltip slides upwards, it ends up covering up the button the mouse is over until the animation finishes. As a result, you have to wait for the animation to finish before you can click, and sometimes the animation replays, as the tooltip itself becomes hovered, causing the tooltip to disappear.

[GIFV](http://i.imgur.com/M1RxCDY.gifv)
![GIF](http://i.imgur.com/M1RxCDY.gif)
![Screenshot](http://i.imgur.com/lggb5t6.png)

I use this package and was searching to see if anyone has had the same issue I did.
They already have a workaround in place, which is
```
.tooltip {
  transition: opacity 500ms;
}
```
This makes the tooltip appear in its final position, which stops this problem.
**This effects platformio-atom-ide-terminal, but it most likely affects any small item with a tooltip**

A better fix would be...
```
.tooltip {
  pointer-events: none;
}
```
http://caniuse.com/#search=pointer

**Comment by silvestreh** [comment]
This is fixed in Material UI `2.0`. It's available for Atom 1.17-beta users!
