### ISSUE TITLE
Rename "Accent" color to "Secondary" to avoid confusion

### ISSUE THREAD

**Issue by bajanbentley** [atom-material/atom-material-ui#356]
The primary theme colour option changes the accent colour instead. Meanwhile the accent colour picker doesn't do anything.

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](http://i.imgur.com/ADrDPWl.png)

**Atom version:** [1.14.2]
**OS and version:** [Ubuntu 16.10]

**Comment by silvestreh** [comment]
This is not an issue. It's designed to be like this. I *should* rename _Accent_ to _Secondary_ to avoid confusion.

The accent color will be used to underline tabs when you have "tinted tab bar" enabled. I see how can this be confusing, but it's a naming issue 😄 

I'll leave this issue open as a reminder of what I have to do.


Thanks!

**Comment by bajanbentley** [comment]
Oho, thanks for the clarification :)

**Comment by silvestreh** [comment]
This is fixed in `2.0` which is available for Atom 1.17-beta users.
