### ISSUE TITLE
Only one styled window on restarting atom

### ISSUE THREAD

**Issue by rasenplanscher** [atom-material/atom-material-ui#360]
Only the first window gets user styles when atom is restarted with multiple windows.

**Reproduction Steps:**

1. Change theme settings to `Purple`, with custom colors
2. Open multiple windows
3. Exit and re-start atom

**Expected behavior:**

All windows should have the custom styles all the time

**Observed behavior:**

All new windows get the custom styles during step 2. After step 3, only one window has the custom styles.

**Screenshots and GIFs**

![wrong-colors](https://cloud.githubusercontent.com/assets/445565/23202293/a43c6b7c-f8dd-11e6-92a0-b59b4627d769.png)

**Atom version:** 1.14.3
**OS and version:** Windows 7

**Installed packages:**

+ atom-beautify
+ atom-line-to-console
+ atom-material-syntax
+ atom-material-syntax-dark
+ atom-material-ui
+ auto-indent
+ blame
+ column-select
+ duplicate-line-or-selection
+ editorconfig
+ emmet
+ git-blame
+ git-line
+ language-gradle
+ markdown-pdf
+ markdown-preview-plus
+ markdown-scroll-sync
+ markdown-writer
+ minimap
+ minimap-codeglance
+ minimap-cursorline
+ minimap-git-diff
+ minimap-selection
+ nuclide
+ react
+ selection-counter
+ simple-drag-drop-text
+ sort-lines
+ sublime-block-comment
+ Sublime-Style-Column-Selection
+ text-manipulation
+ Zen

**Comment by rasenplanscher** [comment]
May be connected to #243

**Comment by silvestreh** [comment]
This is fixed in Material UI `2.0` (available for Atom 1.17-beta). Upon restarting Atom all opened windows get the latest color (and all windows update the colors when changing from one)
