### ISSUE TITLE
Markdown table headers unreadable when saved to HTML from markdown preview.

### ISSUE THREAD

**Issue by BestWillInTheWorld** [atom-material/atom-material-ui#361]
Markdown table headers unreadable when saved to HTML from markdown preview.

## Reproduction Steps:

1. Create/save a markdown file containing a table e.g.

My     | Table
------ | ------
some | value

2. Bring up "markdown preview" using [ctrl]+[m]
3. Right-click in the markdown preview pane and select "save markdown as HTML"
4. 

## Expected behaviour
UI theme shouldn't affect Markdown Preview's [save as HTML]
## Observed behaviour
Open the HTML file in a browser and observe the background color of the header text is dark and so is the text, making it unreadable.  Switch UI Theme away from Atom Material & repeat = problem goes away (but can't use the theme).

![table when saved as html](https://cloud.githubusercontent.com/assets/5352909/23220155/fd42bef2-f918-11e6-9ec4-1095973e57c6.PNG)
![table when saved as html with atom material](https://cloud.githubusercontent.com/assets/5352909/23220156/fd449e5c-f918-11e6-9422-c2c473d88af6.PNG)

**Atom version:** 1.14.3
**OS and version:** Win7

**Installed packages:**

### Markdown Packages in use
In case there are interactions with other packages:
- https://atom.io/packages/markdown-preview
- https://atom.io/packages/markdown-preview-plus
- https://atom.io/packages/markdown-writer
- https://atom.io/packages/markdown-scroll-sync

### Themes in Use
* UI: Atom Material
* Syntax: One Dark

**Comment by silvestreh** [comment]
This is fixed in `2.0` which is available for Atom 1.17-beta users.
