### ISSUE TITLE
Parts of screen randomly becoming white and then reverting back

### ISSUE THREAD

**Issue by AtomicCoding** [atom-material/atom-material-ui#365]
Hello, the issue is that whenever I go through an interface or open a new window or something, part of the screen will be white for a moment and then go back.

**Reproduction Steps:**

1. Enter some sort of new interface

**Expected behavior:**

No random white areas in Atom.

**Observed behavior:**

White areas in Atom.

**Screenshots and GIFs**
http://i.imgur.com/66phrn6.gifv

**Atom version:** 1.14.4
**OS and version:** MacOS Sierra, 10.12.3

**Installed packages:**

All Core Packages and built-in ones(Of Course)
Hydrogen
advanced-open-file
atom-beautify
atom-bootstrap4
atom-clock
atom-itunes
atom-jade
atom-ternjs
autocomplete-java
autocomplete-json
autocomplete-modules
autocomplete-python
color-picker
emmet
file-icons
gcc-make-run
git-plus
hey-pane
intentions
javascript-snippets
kite
language-minecraft-forge-cfg
linter
linter-clang
linter-erb
linter-jsonlint
linter-sass-lint
linter-tidy
linter-write-good
minimap
minimap-find-and-replace
minimap-pigments
open-this
open-unsupported-files
pdf-view
pigments
qolor
script
undo-tree
zentabs
platformio-ide-terminal
(I know, I have too many packages)

**Comment by silvestreh** [comment]
I can't reproduce this :-/

**Comment by bcotrim** [comment]
Same behaviour here.

Atom 1.15.0
MacOS Sierra 10.12.4

http://imgur.com/kghh9LJ

**Comment by silvestreh** [comment]
@bcotrim do you have any packages in common with @AtomicCoding?

**Comment by bcotrim** [comment]
common packages:
- file-icons
- intentions
- javascript-snippets
- linter

**Comment by silvestreh** [comment]
cool! that narrows things down. thanks! I'll take a look 😃

**Comment by bcotrim** [comment]
Was doing some more research on this and found the cause/workaround for it.
Seems to be completely unrelated to atom-material-ui.

https://github.com/atom/atom/issues/12634

**Comment by backlands** [comment]
I was experiencing this issue as well and thanks to @bcotrim for pointing out the core atom issue (https://github.com/atom/atom/issues/12634). Looks like this issue will be patched in Atom 1.19 when released. Until then use the snippet `body { opacity: 0.99 }` in your stylesheet.

Applying that snippet resolved the problem, with that this issue can probably be closed since it is shown to be caused by Atom Core not this package.

**Comment by AtomicCoding** [comment]
Thanks @backlands for the help. I have closed the issue.
