### ISSUE TITLE
Tree View Line Separator 

### ISSUE THREAD

**Issue by scooterman751** [atom-material/atom-material-ui#366]
There is no line separator for the tree view with the Atom-Material UI. I really don't like this since it mixes me up with my open files ( tabs ) and the tree view. I really like this UI and just adding that line would be very helpful! Thanks! 

**Reproduction Steps:**
1. Downloaded atom-material-ui [https://atom.io/themes/atom-material-ui]
2. Opened tree view 

I thought that everything was going to be normal and the tree view would look fine but the tree view didn't have any separating line and made it look a bit weird. 

**Screenshots and GIFs**

![image](https://cloud.githubusercontent.com/assets/22735586/23681788/6daa5b38-035e-11e7-9766-0a84eacfd2e4.png)

![image](https://cloud.githubusercontent.com/assets/22735586/23681813/82faaaa6-035e-11e7-8143-156333efa47a.png)

**Atom version:** [1.14.4]
**OS and version:** [Windows 10]

**Installed packages:**

[Emmet, Color-Picker, Minimap]

**Comment by silvestreh** [comment]
You could enable shadows 😃
