### ISSUE TITLE
"Define a working set" of Nuclide's tree-view is misplaced

### ISSUE THREAD

**Issue by LingRay** [atom-material/atom-material-ui#367]
[Short description of problem here]
The btn of "Define a working set" is too small。
**Screenshots and GIFs**
![image](https://cloud.githubusercontent.com/assets/12709688/23688642/b7fb50a6-03f0-11e7-9d87-16b8f4e0c819.png)

**Atom version:** 1.14.3
**OS and version:** macOS

**Comment by LingRay** [comment]
resolve it using the css style  
`    .nuclide-file-tree-toolbar .btn-group .btn {
    padding: 0;
    width: 8rem;
    border-radius: 0;
    margin-bottom: 1rem;
}`

**Comment by silvestreh** [comment]
This is fixed in `2.0` available for Atom 1.17-beta. No more special styles for Nuclide, it works out of the box! 🎉
