### ISSUE TITLE
Shift-Enter doesn't trigger Button Press in Command Palette (e.g. for git-plus)

### ISSUE THREAD

**Issue by timomeh** [atom-material/atom-material-ui#368]
**Reproduction Steps:**

1. Install git-plus
2. Stage some files with git-plus in the command palette
3. Press <kbd>shift-enter</kbd>

**Expected behavior:**

Pressing <kbd>shift-enter</kbd> should cause the flagged files to be staged, or rather trigger a press on the "Apply" button.

**Observed behavior:**

<kbd>shift-enter</kbd> doesn't work in atom-material-ui, but it works in Themes like OneDark.

**Screenshots and GIFs**

![mar-10-2017 13-35-22](https://cloud.githubusercontent.com/assets/4227520/23795538/7574be8c-0596-11e7-8d75-d2c10afc1ae1.gif)

(I'm pressing shift-enter at the end, but I'm too lazy to use a keycaster. 😄) 

**Atom version:** 1.14.4
**OS and version:** macOS 10.12.3

**Installed packages:**

```
Community Packages (30)
├── Zen@0.16.4
├── advanced-open-file@0.16.5
├── atom-material-syntax@1.0.2
├── atom-material-syntax-dark@0.2.7
├── atom-material-ui@1.3.9
├── atom-ternjs@0.18.2
├── autocomplete-modules@1.6.7
├── copy-with-syntax@0.0.3
├── docblockr@0.9.1
├── editorconfig@2.2.2
├── emmet@2.4.3
├── file-icons@2.0.17
├── flow-ide@1.3.0
├── git-history@3.2.0
├── git-plus@7.3.3
├── hey-pane@0.2.2
├── jumpy@3.1.3
├── language-babel@2.56.0
├── less-than-slash@0.16.0
├── linter@1.11.23
├── linter-eslint@8.1.2
├── linter-js-standard@3.9.0
├── markdown-toc@0.4.2
├── minimap@4.26.8
├── minimap-autohide@0.10.1
├── narrow@0.36.0
├── pigments@0.39.0
├── project-manager@3.3.3
├── split-selection-into-cursors@0.2.0
└── vim-mode-plus@0.82.3
```

**Bonus Points:**

- The Buttons in the command palette could look a bit better (position/margin, shadow, ...)
- The labels of the items (like `?` and `M` in the GIF) could have more padding

I take a look at this later to open maybe a PR, but I can't promise anything, also because I don't know if I know where to start. 😄

**Comment by silvestreh** [comment]
I agree about the looks, I'm actually working on a new codebase to mitigate these kind of issues.

About the <kbd>Shift</kbd>+<kbd>↩</kbd>… it's weird because I did not set nor overrode any event listeners. Are you sure it's caused by this theme?

**Comment by timomeh** [comment]
Oh my god that's so embarrassing... I've recently overridden <kbd>shift-enter</kbd>, at the same time as I switched to atom-material-ui. I totally forgot about that. 😥

Yeah. <kbd>shift-enter</kbd> works. I'm sorry for that. Totally my fault.

As you said, an improvement of the looks would be great. But the keystroke works, so I'm closing this.

**Comment by silvestreh** [comment]
@timomeh nothing to be embarrassed of! You wouldn't believe the times where I found myself blocked because of a small, almost obvious, little issue. It happens more often than I'd like to admit. 😁
