### ISSUE TITLE
Error Annotation Table in Linter 2.0

### ISSUE THREAD

**Issue by ghost** [atom-material/atom-material-ui#369]
Many thanks for all your work on the UI!

After the atom linter got updated to ver. 2 the status bar annotation was changed to a table with three numbers. The colors of the small boxes and fonts are taken from the UI and I was wondering if it would be possible to modify them so there are a bit easier to read and look cleaner? Thanks in advance for considering this.

![screenshot from 2017-03-15 23-54-46](https://cloud.githubusercontent.com/assets/18163728/23954942/dd976c3c-09db-11e7-936e-8b3664fb3760.png)
![screenshot from 2017-03-16 00-01-51](https://cloud.githubusercontent.com/assets/18163728/23954945/de013176-09db-11e7-97ec-848cdc88c941.png)

**Comment by silvestreh** [comment]
I'll take a look. I'm focusing on the 2.0 branch, but that will require Atom 1.17 (currently not even in Beta)

**Comment by JLCCI** [comment]
Great, many people are using the linter package so I am sure it would be really appreciated. Keep up the good work.

**Comment by JGH1000** [comment]
+1

The font color depends on accent it seems. Also a different color for the small boxes would be nice (or no boxes at all would be even better).

![screenshot from 2017-04-27 13-09-07](https://cloud.githubusercontent.com/assets/27884805/25467653/a6d66e24-2b4a-11e7-84e2-93dab86838aa.png)

**Comment by silvestreh** [comment]
This is what it looks like in the `2.0` branch.

<img width="71" alt="captura de pantalla 2017-04-27 a la s 14 30 19" src="https://cloud.githubusercontent.com/assets/1133339/25496101/1b412046-2b56-11e7-9d44-25d44009aa9e.png">

I'm not making color adjustments specifically for linter, so it'll pick up the theme's variables.

**Comment by silvestreh** [comment]
Turns out it didn't look quite alright with a light syntax theme, so I ended up touching the colors a bit in the end… here's what it'll look like when Atom 1.17 hits!

<img width="72" alt="captura de pantalla 2017-04-27 a la s 14 40 15" src="https://cloud.githubusercontent.com/assets/1133339/25496492/9045d50c-2b57-11e7-858a-da36ee4b5855.png"> <img width="67" alt="captura de pantalla 2017-04-27 a la s 14 40 29" src="https://cloud.githubusercontent.com/assets/1133339/25496494/90b5667e-2b57-11e7-910b-46bf8969c50b.png">

**Comment by Arcanemagus** [comment]
@silvestreh If there are things that should be fixed in `linter-ui-default` instead of here feel free to file issues. I know @steelbrain isn't a UI guy, and I don't really know it either, so I'm sure there are things that are being done wrong there 😉.

**Comment by silvestreh** [comment]
@Arcanemagus Material UI was to blame for this one in particular (looks just fine on One Light/Dark). But yeah, I'll sure file an issue or send a PR if I find something off in `linter-ui-default` :)

**Comment by silvestreh** [comment]
This is fixed in `2.0` available for Atom 1.17-beta.
