### ISSUE TITLE
rror: Cannot find module 'tinycolor2'     at Module._resolveFilename (module.js:336:15)     

### ISSUE THREAD

**Issue by Karmaliu** [atom-material/atom-material-ui#370]
[Short description of problem here]

**Reproduction Steps:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Atom version:** [Enter Atom version here]
**OS and version:** [Enter OS name and version here]

**Installed packages:**

[List of installed packages here]

**Comment by silvestreh** [comment]
Please, search the closed issues before opening a new one. This has been answered quite a few times already.

For some reason, APM fails to install the required dependencies. Open a terminal and…

```shell
cd ~/.atom/packages/atom-material-ui/
npm install
```

Or, just reinstall from within Atom.
