### ISSUE TITLE
Link to redisigned Atom icon on dropbox don't work

### ISSUE THREAD

**Issue by afishr** [atom-material/atom-material-ui#373]
I just get 404 error when I follow the link to Atom icon on dropbox. 
Please, reupload the archive with those beautiful icons.

**Comment by silvestreh** [comment]
You're right! I don't know how, but the old link expired or something 😕 … Here's the new one: https://www.dropbox.com/s/8gyn40sw95626dx/Atom-MD-Icon.zip?dl=0 (also updated in the README file)
