### ISSUE TITLE
Main bar's title shows up too dark

### ISSUE THREAD

**Issue by niccolomineo** [atom-material/atom-material-ui#374]
Main bar's title shows up with a dark colour, making it nearly impossible to read.

**Reproduction Steps:**

1. Open Atom's Preferences panel
2. Select the "Core" tab
3. Enable "Use Custom Title Bar"

**Expected behavior:**

Main bar's title should be of a lighter color (e.g. the one showing up when the window is out of focus).

**Observed behavior:**

Main bar's title appears black

**Screenshots and GIFs**

![title](https://cloud.githubusercontent.com/assets/5409469/24313373/d0288b64-10dc-11e7-8b77-f23b8d19e465.png)

**Atom version:** 1.15.0
**OS and version:** Mac OS Sierra 10.12.3

**Installed packages:**
Remote-FTP, atom-autocomplete-php, atom-beautify, atom-material-ui, atom-meld, autocomplete-json, autocomplete-python, autocomplete-xml, busy-signal, camel-select, highlight-selected, intellij-darcula-syntax, intentions, language-sql-mysql, linter, linter-jshint, linter-php, linter-ui-default, markdown-preview-plus, platformio-ide-terminal, symbols-tree-view, todo-show, 
tree-view-git-status

**Comment by silvestreh** [comment]
This is fixed in `2.0` available for Atom 1.17-beta.
