### ISSUE TITLE
No visual feedback on where exactly to click to close a tab

### ISSUE THREAD

**Issue by takeontom** [atom-material/atom-material-ui#377]
It's difficult to know where exactly to click on a tab to close it.

**Reproduction Steps:**

1. Open a file in Atom
2. Place your mouse on the left hand side of the file's tab
3. Move your mouse gradually closer to the tab's `x` icon, clicking continuously, and try to guess when your click will actually close the tab.

**Expected behavior:**

I'd expect one, some or all of these to happen:

* The tab's close icon to not appear until the mouse is over the close icon's hitbox
* The icon's hitbox to have a background colour
* The mouse cursor to only change to the pointer cursor when the mouse is over the close icon's hitbox

**Observed behavior:**

When hovering anywhere over a file's tab, the close icon appears and the mouse cursor turns to the pointer cursor (the hand). When the mouse cursor is in range of the tab's close button there's no visual indication - making it surprisingly difficult to know if your click is going to close the tab or not.

**Screenshots and GIFs**

Annoyingly I can't take a screenshot and keep the pointer icon - so you'll have to imagine you're seeing the pointer mouse cursor on all the screenshots below. :)

![image](https://cloud.githubusercontent.com/assets/423709/25000448/435f2d8e-2039-11e7-8de6-0d0b160c7580.png)

Which of these would cause the tab to close?

![1](https://cloud.githubusercontent.com/assets/423709/25000245/7e5e6a04-2038-11e7-9e08-4368f4a71603.png)
![2](https://cloud.githubusercontent.com/assets/423709/25000248/8220d2bc-2038-11e7-90ab-815057ee2d24.png)
![3](https://cloud.githubusercontent.com/assets/423709/25000249/8428c81c-2038-11e7-91de-9324df78c771.png)
![4](https://cloud.githubusercontent.com/assets/423709/25000250/864c3412-2038-11e7-89af-544b6ac1e82f.png)

**Atom version:**

```
$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**OS and version:** Ubuntu 16.04

**Installed packages:**

```
$ apm list
Built-in Atom Packages (87)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.9.1
├── one-light-ui@1.9.1
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.2
├── archive-view@0.62.2
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.15.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.34.2
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.0
├── background-tips@0.26.1
├── bookmarks@0.44.1
├── bracket-matcher@0.85.2
├── command-palette@0.40.1
├── deprecation-cop@0.56.2
├── dev-live-reload@0.47.0
├── encoding-selector@0.23.1
├── find-and-replace@0.206.3
├── fuzzy-finder@1.4.1
├── git-diff@1.3.1
├── go-to-line@0.32.0
├── grammar-selector@0.49.1
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.36.1
├── line-ending-selector@0.6.1
├── link@0.31.2
├── markdown-preview@0.159.6
├── notifications@0.66.2
├── open-on-github@1.2.1
├── package-generator@1.1.0
├── settings-view@0.247.0
├── snippets@1.0.5
├── spell-check@0.70.2
├── status-bar@1.8.1
├── styleguide@0.49.2
├── symbols-view@0.114.0
├── tabs@0.104.1
├── timecop@0.34.0
├── tree-view@0.214.1
├── update-package-dependencies@0.10.0
├── welcome@0.36.0
├── whitespace@0.36.2
├── wrap-guide@0.39.0
├── language-c@0.56.0
├── language-clojure@0.22.2
├── language-coffee-script@0.48.5
├── language-csharp@0.14.2
├── language-css@0.42.0
├── language-gfm@0.88.1
├── language-git@0.19.0
├── language-go@0.43.1
├── language-html@0.47.2
├── language-hyperlink@0.16.1
├── language-java@0.26.0
├── language-javascript@0.126.1
├── language-json@0.18.3
├── language-less@0.30.1
├── language-make@0.22.3
├── language-mustache@0.13.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.4
├── language-property-list@0.9.0
├── language-python@0.45.2
├── language-ruby@0.70.5
├── language-ruby-on-rails@0.25.2
├── language-sass@0.57.1
├── language-shellscript@0.25.0
├── language-source@0.9.0
├── language-sql@0.25.3
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.16
└── language-yaml@0.28.0

Community Packages (28) /home/tom/.atom/packages
├── ariake-dark-syntax@0.1.3
├── atom-isort@1.2.5
├── atom-material-syntax@1.0.2
├── atom-material-ui@1.3.9
├── atom-overtype-mode@0.3.4
├── autocomplete-python@1.8.63
├── autoupdate-packages@1.3.1
├── busy-signal@1.3.0
├── color-picker@2.2.5
├── hey-pane@0.2.2
├── intentions@1.1.2
├── language-restructuredtext@1.1.0
├── linter@2.1.2
├── linter-flake8@2.1.5
├── linter-jshint@3.0.3
├── linter-ui-default@1.2.2
├── minimap@4.27.1
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-linter@2.0.0
├── nord-atom-syntax@0.8.0
├── nord-atom-ui@0.11.0
├── project-manager@3.3.4
├── python-autopep8@0.1.3
├── python-indent@1.0.2
├── python-tools@0.6.9
└── sync-settings@0.8.1
```

**Comment by silvestreh** [comment]
This is fixed in `2.0` available for Atom 1.17-beta.
