### ISSUE TITLE
reduce padding

### ISSUE THREAD

**Issue by bearcott** [atom-material/atom-material-ui#385]
can reduce or at least have a setting to reduce padding on.. everything? 

I can see 20 items in the tree view when I normally can see 50. Tabs are more congested, my settings view is now magnified.

I don't understand how such a large amount of people are using this package when the spacing is so awful.

**Comment by silvestreh** [comment]
You can make the tree-view more compact within the theme's settings. I'm working on 2.0 which will be compact by default.

**Comment by daftscience** [comment]
I agree with @silvestreh, the compact tree view does help. And so does decreasing the UI font size. 

I can't figure out how to fix the spacing in forms and panels though.

![capture](https://cloud.githubusercontent.com/assets/2718662/25558974/4f2a5a9c-2cf7-11e7-9b07-854e74b51288.PNG)

I have to tab to reach the things at the bottom.

**Comment by silvestreh** [comment]
@daftscience which package provides that UI so I can take a look?

**Comment by daftscience** [comment]
It's this one: [remote-sync](https://atom.io/packages/remote-sync)

**Comment by manoskav** [comment]
Hello,
There is similar problem with Platformio. The size of buttons and selections are abnormally huge.
![screenshot_1](https://cloud.githubusercontent.com/assets/22129821/25597159/e9146fa0-2ed5-11e7-92cf-913eaa349ff5.png)

**Comment by silvestreh** [comment]
@manoskav yeah, that one's fixed in `2.0`.

**Comment by silvestreh** [comment]
@daftscience for some reason I can't bring up that UI using `remote-sync`… are there any extra non-obvious steps that I should take?

**Comment by daftscience** [comment]
@silvestreh yeah, if you right click on a folder and select "Remote Sync" -> "Configure."

**Comment by silvestreh** [comment]
Yeah, I'm not seeing that 😕 

<img width="1361" alt="captura de pantalla 2017-05-04 a la s 17 10 49" src="https://cloud.githubusercontent.com/assets/1133339/25723008/b01cf8ac-30ec-11e7-9cb6-02b5b0fbcc46.png">

**Comment by silvestreh** [comment]
Looks like it might not support Atom 1.17 yet …

**Comment by daftscience** [comment]
Strange. At any rate, it's not much more than a mild inconvenience at this point. I just thought I'd point it out since the issue was open.
