### ISSUE TITLE
Debugging text printed to console

### ISSUE THREAD

**Issue by Arcanemagus** [atom-material/atom-material-ui#388]
Some debugging text is printed to the console.

**Reproduction Steps:**

1. Start Atom with this theme active.
2. Open the developer tools and check the Console.

**Expected behavior:**

Nothing printed to the console when running Atom normally.

**Observed behavior:**

Some debugging text is printed to the console. Perhaps this should be wrapped in a check on [`atom.inDevMode()`](https://atom.io/docs/api/v1.16.0/AtomEnvironment#instance-inDevMode)?

**Screenshots and GIFs**

![image](https://cloud.githubusercontent.com/assets/427137/25715660/23e4fdde-30b1-11e7-9788-0adeadfc46ad.png)

**Atom version:**
v1.17.0-beta4
**OS and version:**
Windows 10 x64

**Comment by silvestreh** [comment]
Yeah, I completely forgot about it 😅 … I *think* I already removed those logs in my local copy.

**Comment by Arcanemagus** [comment]
Closing since it's fixed in the repo then 😉.
