### ISSUE TITLE
The theme shows black text on a gray background with the Markdown Preview package.

### ISSUE THREAD

**Issue by haykam821** [atom-material/atom-material-ui#391]
Like the title says, whenever I use the GitHub-flavored Markdown preview style alongside the Material UI theme, there is a black font on a gray background.

**Reproduction Steps:**

1. Download the Markdown Preview (`markdown-preview`) package from Atom
2. Enable 'Use GitHub.com style' in the package's settings
3. Create a Markdown document that has any table in it.
4. Open the Markdown Preview's pane for previewing Markdown documents.

**Expected behavior:**

The font color changes to match the dark background of the header table's cell.

**Observed behavior:**

The font color is black, which is unreadable and ugly when put on top of the Material Design gray.

**Screenshot**

This image should show the problem.

![image](https://cloud.githubusercontent.com/assets/24855774/25880480/9f60d53e-3505-11e7-9382-36798d3c1cec.png)

**Atom version:** 1.16.0 x64
**OS and version:** macOS Sierra (10.12.4, build 16E195)

**Installed packages:**

* `release-notes`
* `about`
* `markdown-preview`
* `autosave`
* all other core packages

**Comment by silvestreh** [comment]
It's fixed in Material UI `2.0` (only available for Atom 1.17 which is still in beta) 😃

**Comment by suhanselvan-wft** [comment]
`subnet-text`
