### ISSUE TITLE
Dropbox link for icon is 404

### ISSUE THREAD

**Issue by Log1x** [atom-material/atom-material-ui#392]
Dropbox link for icon is dead.

**Reproduction Steps:**

1. Go to https://dl.dropboxusercontent.com/u/115930/Atom-MD-Icon.zip
2. 404 - File not found

**Comment by silvestreh** [comment]
Seems to be happening from time to time… It's on https://www.dropbox.com/s/8gyn40sw95626dx/Atom-MD-Icon.zip?dl=0 … I'll update the README.
