### ISSUE TITLE
Horizontal scroll of tree is partially unclickable and not highlighted from the UI

### ISSUE THREAD

**Issue by jamby** [atom-material/atom-material-ui#399]
Horizontal scroll of tree is partially unclickable and not highlighted from the UI

**Reproduction Steps:**

1. Create a few folders that will make a horizontal scroll inside the project
2. Select one of the deeply nested folders/files
3. Observe how it is unable to be clicked on at a certain point and the highlight is not covering the full length of the file

**Expected behavior:**

Should be able to click it at the line it is on and that it should be highlighted for the full length of the tree's horizontal scroll

**Observed behavior:**

Unable to click on file/folder if it is too far horizontally to the right. Highlight is not covering full length of tree

**Screenshots and GIFs**

![image](https://cloud.githubusercontent.com/assets/250728/26162617/364d066c-3af5-11e7-888c-be10e555b3a7.png)

**Atom version:** 1.17.0
**OS and version:** macOS 10.12.2

**Installed packages:**

```
Sublime-Style-Column-Selection@1.7.4
advanced-open-file@0.16.6
aligner@1.1.0
atom-css-comb@3.1.0
atom-elixir@0.2.3
atom-fuzzy-grep@0.16.0
atom-material-syntax-dark@0.2.7
atom-material-ui@2.0.3
atom-ternjs@0.18.3
autocomplete-elixir@1.5.14
autocomplete-modules@1.6.10
autocomplete-paths@1.0.5
autocomplete-ruby@0.2.8
blame@0.10.3
block-travel@1.0.5
busy-signal@1.4.1
cucumber@0.6.0
cucumber-step@0.2.0
ex-mode@0.14.0
file-icons@2.1.5
gist-it@0.9.2
git-history@3.3.0
highlight-selected@0.13.1
intentions@1.1.2
language-babel@2.61.0
language-diff@0.7.0
language-elixir@0.17.0
language-haml@0.24.2
language-viml@1.1.3
linter@2.1.4
linter-elixir-credo@1.1.0
linter-eslint@8.1.7
linter-rubocop@2.1.1
linter-ui-default@1.5.0
merge-conflicts@1.4.5
minimap@4.28.2
minimap-find-and-replace@4.5.2
minimap-git-diff@4.3.1
minimap-highlight-selected@4.6.1
pigments@0.39.1
pretty-json@1.6.3
rails-latest-migration@1.1.6
react-snippets@0.7.2
toggle-quotes@1.0.1
vim-mode@0.66.0
```

**Comment by silvestreh** [comment]
This should probably be fixed in the `tree-view` package as all themes are affected by this issue.
