### ISSUE TITLE
Search results don't keep specified color when highlighting file

### ISSUE THREAD

**Issue by jamby** [atom-material/atom-material-ui#400]
When inside search results from searching for something, the highlight of a file name does not keep the specified color (in my case, Orange).

**Reproduction Steps:**

1. Have a non-default color for your Atom Material UI
2. Search for something in the project
3. Project Find Results page should show up with multiple files
4. Highlight a file by clicking on it (may close the results for that file, but that's fine)
5. Click away from Atom, and note that it changes to the teal color.

**Expected behavior:**

When clicking away from Atom while on the Project Find Results page, it should keep the specified color.

**Observed behavior:**

When clicking away from Atom while on the Project Find Results page, it reverts back to the teal default color and then my color if I click back onto Atom.

**Screenshots and GIFs**

![kapture 2017-05-17 at 15 46 37](https://cloud.githubusercontent.com/assets/250728/26173075/8cb9cc1a-3b18-11e7-898b-313cb086b708.gif)

**Atom version:** 1.17.0
**OS and version:** macOS 10.12.2

**Installed packages:**

```
Sublime-Style-Column-Selection@1.7.4
advanced-open-file@0.16.6
aligner@1.1.0
atom-css-comb@3.1.0
atom-elixir@0.2.3
atom-fuzzy-grep@0.16.0
atom-material-syntax-dark@0.2.7
atom-material-ui@2.0.3
atom-ternjs@0.18.3
autocomplete-elixir@1.5.14
autocomplete-modules@1.6.10
autocomplete-paths@1.0.5
autocomplete-ruby@0.2.8
blame@0.10.3
block-travel@1.0.5
busy-signal@1.4.1
cucumber@0.6.0
cucumber-step@0.2.0
ex-mode@0.14.0
file-icons@2.1.5
gist-it@0.9.2
git-history@3.3.0
highlight-selected@0.13.1
intentions@1.1.2
language-babel@2.61.0
language-diff@0.7.0
language-elixir@0.17.0
language-haml@0.24.2
language-viml@1.1.3
linter@2.1.4
linter-elixir-credo@1.1.0
linter-eslint@8.1.7
linter-rubocop@2.1.1
linter-ui-default@1.5.0
merge-conflicts@1.4.5
minimap@4.28.2
minimap-find-and-replace@4.5.2
minimap-git-diff@4.3.1
minimap-highlight-selected@4.6.1
pigments@0.39.1
pretty-json@1.6.3
rails-latest-migration@1.1.6
react-snippets@0.7.2
toggle-quotes@1.0.1
vim-mode@0.66.0
```

**Comment by brandon14** [comment]
Can confirm this is happening to me too on both Atom 1.17.0 and 1.18.0-beta0 with material-ui 2.0.3.

**Comment by silvestreh** [comment]
Yep, I also noticed it, but since it wasn't breaking anything I decided to live with it while working on other stuff. It seems to be a problem with how the lists are styled. I'll look into it!

**Comment by jamby** [comment]
For sure, it definitely wasn't a "this needs to be fixed now" issue. More of a documentation of it. Since this is rather low priority.

There are much higher priority things to be fixed! I may look into it at some point to fix it myself if I get a chance.
