### ISSUE TITLE
Theme related issue on new linter tooltips

### ISSUE THREAD

**Issue by pingshunhuangalex** [atom-material/atom-material-ui#402]
Hi @silvestreh 
I was just told that there is a theme related issue on new linter tooltips as you can see in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/17170199/26180835/38bf760e-3baf-11e7-8498-b7a105afc0e1.png)

It can be fixed using `@background-color-highlight` as the tooltip background color, so it won't show up as transparent, as explained in [steelbrain/linter-ui-default#309](https://github.com/steelbrain/linter-ui-default/issues/309).

Thanks.

**Comment by silvestreh** [comment]
Looks like this was fixed in https://github.com/steelbrain/linter-ui-default/pull/321
