### ISSUE TITLE
Tree view issue

### ISSUE THREAD

**Issue by giolf** [atom-material/atom-material-ui#404]
I figure out that problem on my tree view:
![image](https://cloud.githubusercontent.com/assets/6743233/26206167/55bff2b2-3be4-11e7-8508-0545acf93868.png)
it's seem that the highlighted folder or file selection is fixed with the tree-view width.

**Comment by silvestreh** [comment]
Yeah, I noticed this too. It also happens with default themes (One Dark/Light and Atom Dark/Light) so I didn't give it much thought.

**Comment by giolf** [comment]
Yes you're complete right ! it happens even with the default template.  
(just to give you an idea about i'm fan of your theme):

1.  Setup atom to my new machine
2. Install material theme
3. work

**Comment by giolf** [comment]
Would be  great if someone could find a temporary solution in the meanwhile of an update from Atom

**Comment by FNGR2911** [comment]
@giolf look at this comment: [](https://github.com/atom-material/atom-material-ui/issues/394#issuecomment-302123319)

**Comment by giolf** [comment]
@FNGR2911 i check that comment ... but they're speaking about another issue related to the compact menu sidebar ... right ?

**Comment by FNGR2911** [comment]
@giolf you're right, sorry!

**Comment by willviles** [comment]
+1 on @giolf's issue. Toggling the 'Tree View Compact List' option doesn't work after updating to the latest Atom 1.17.0.

**Comment by silvestreh** [comment]
@willviles the compact feature was removed altogether. #394 has more info about it.
