### ISSUE TITLE
List of projects can't scroll

### ISSUE THREAD

**Issue by Ivorzk** [atom-material/atom-material-ui#405]
![qq 20170519131617](https://cloud.githubusercontent.com/assets/7390138/26234195/6e028342-3c95-11e7-8275-3a467f366bf1.jpg)
Project folder sometimes can't scroll to the left of the tree!Can the old version, the new the emergence of the problem!

**Comment by KerenChandran** [comment]
I'm still having this issue. Is someone looking into it?

**Comment by silvestreh** [comment]
Did you guys update to Material UI 2.0?

**Comment by KerenChandran** [comment]
OMG that was the issue! Didn't notice there was an update. Sorry about that.

**Comment by silvestreh** [comment]
No problem 😃 Enjoy the new Material UI! @Ivorzk did updating solve your problem? By the looks of your screenshot it seems you're still on `1.3.x`

**Comment by mediabeastnz** [comment]
I still have this issue on version 2.0.4
