### ISSUE TITLE
UI Glitch with bottom dock arrow

### ISSUE THREAD

**Issue by brandon14** [atom-material/atom-material-ui#408]
The linter-ui-default package adds a dock to the bottom of the page that when expanded,s shows the linter information for the current file. Sometimes when the arrow to expand the dock shows, the will be a black rectangle that shows around the up arrow. I switched the theme back to Atom Dark and was never able to reproduce it, and same with the One Dark theme. It also seems to occur randomly and not everytime that dock expand arrow is shown does it glitch. I have provided a screen shot showing the black rectangle.

**Reproduction Steps:**

1. Apply Material UI theme
2. Have an extension like linter-ui-default that adds a bottom dock
3. Hover over the statusbar to show the expand handle for the bottom dock

**Expected behavior:**

No graphical glitch appears.

**Observed behavior:**

A black rectangle will appear around the dock expansion handle.

**Screenshots and GIFs**

![dock-glitch-material-ui](https://cloud.githubusercontent.com/assets/1152696/26253719/525dbc6e-3c82-11e7-8107-ce3f407cb397.png)

**Atom version:** 1.18.0-beta0
**OS and version:** Windows 7

**Installed packages:**

advanced-open-file@0.16.6
aligner@1.2.0
aligner-css@1.2.1
aligner-javascript@1.1.0
aligner-php@1.1.1
aligner-scss@1.3.0
angularjs@0.4.0
atom-autocomplete-php@0.22.2
atom-beautify@0.29.24
atom-bracket-highlight@0.3.2
atom-clock@0.1.7
atom-css-comb@3.1.0
atom-material-syntax-dark@1.0.0
atom-material-ui@2.0.3
atom-save-all@0.4.1
atom-ternjs@0.18.3
auto-detect-indentation@1.3.0
autoclose-html@0.23.0
autocomplete-modules@1.6.10
busy-signal@1.4.1
color-picker@2.2.5
custom-title@1.0.1
declarations@1.1.3
declarations-js@1.0.2
docblockr@0.10.1
editorconfig@2.2.2
emmet@2.4.3
figletify@0.2.2
file-icons@2.1.6
file-types@0.5.5
fonts@2.1.0
git-line@0.6.0
git-time-machine@1.5.9
gitignore-snippets@0.2.5
highlight-line@0.12.0
hyperclick@0.0.40
hyperclick-php@0.2.1
intentions@1.1.2
intentions-colorpicker@1.0.1
javascript-snippets@1.2.1
js-hyperclick@1.11.0
jsdoc-generator@0.2.3
keybinding-cheatsheet@0.1.1
language-blade@0.30.0
language-generic-config@1.3.0
language-gitignore@0.3.0
language-htaccess@0.1.1
language-javascript-jsx@0.3.7
language-todo-extra-words@0.2.0
linter@2.1.4
linter-eslint@8.1.7
linter-htmlhint@1.3.3
linter-php@1.3.2
linter-ui-default@1.5.4
linter-write-good@0.9.0
markdown-pdf@1.5.0
markdown-writer@2.6.5
merge-conflicts@1.4.5
minimap@4.28.2
minimap-codeglance@0.4.6
minimap-find-and-replace@4.5.2
minimap-git-diff@4.3.1
minimap-linter@2.0.0
minimap-quick-highlight@1.0.1
minimap-selection@4.4.0
open-recent@5.0.0
pdf-view@0.58.0
php-composer-completion@0.3.4
php-cs-fixer@4.1.0
php-debug@0.2.4
php-server@0.7.0
project-manager@3.3.4
qolor@0.4.1
quick-highlight@0.10.0
simple-drag-drop-text@0.3.4
sync-settings@0.8.1
tabs-to-spaces@1.0.3
termination@0.5.1
todo-show@1.11.0
underline-trailing-whitespace@1.4.2
wakatime@7.0.3
whitespace@0.36.2

**Comment by silvestreh** [comment]
Looks like you found https://github.com/atom/atom/issues/12634.

**Comment by brandon14** [comment]
Yeah it looks like it. I mean it isn't even a big deal but I figured I would post an issue about it in case no one was aware!
