### ISSUE TITLE
Color tooltip in settings

### ISSUE THREAD

**Issue by jneuendorf** [atom-material/atom-material-ui#409]
The tooltip shows `Default: [object Object]` when hovering on the colored squares for primary and secondary color.

**Reproduction Steps:**

1. Open `atom-material-ui`'s settings from Atom -> Settings -> Themes
2. Hover the color squares in the `Colors` section with the mouse cursor.

**Expected behavior:**

The tooltip contains the currently picked color.
It could contain the predefined color name.
Also it could indicated that the secondary color is generated (like `Value: #123456 (generated)`).

**Observed behavior:**

The tooltip contains `Default: [object Object]`.
(I am not quite sure what `Default` means in this context.)

<img width="615" alt="atom-material-ui_hover" src="https://cloud.githubusercontent.com/assets/6906734/26282016/52b7af80-3e08-11e7-811e-3736412527c8.png">

**Atom version:** 1.17.0
**OS and version:** macOS Sierra 10.12.4 (16E195)

**Installed packages:**

```
Community Packages (45) ~/.atom/packages
├── MagicPython@1.0.10
├── Sublime-Style-Column-Selection@1.7.4
├── atom-beautify@0.29.24
├── atom-material-syntax@1.0.6
├── atom-material-ui@2.0.3
├── autocomplete-paths@1.0.5
├── autocomplete-php@0.3.7
├── autocomplete-ruby@0.2.8
├── autocomplete-sass@0.1.0
├── block-comment@0.4.3
├── busy-signal@1.4.1
├── code-annotations@2.1.3
├── color-picker@2.2.5
├── dash@1.7.1
├── django-templates@0.5.0
├── emmet@2.4.3
├── export-html@3.1.0
├── file-icons@2.1.6
├── highlight-selected@0.13.1
├── html-entities@0.4.0
├── hyperclick@0.0.40
├── imdone-atom@2.2.6
├── intentions@1.1.2
├── js-hyperclick@1.11.0
├── language-latex@1.0.0
├── language-spacebars@0.2.2
├── linter@2.1.4
├── linter-coffeelint@1.2.1
├── linter-flake8@2.2.1
├── linter-htmlhint@1.3.3
├── linter-jshint@3.1.2
├── linter-php@1.3.2
├── linter-ruby@1.2.5
├── linter-ui-default@1.5.4
├── merge-conflicts@1.4.5
├── minimap@4.28.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-pigments@0.2.2
├── pdf-view@0.58.0
├── pigments@0.39.1
├── project-manager@3.3.4
├── sort-lines@0.14.0
├── svg-preview@0.11.0
└── tabs-to-spaces@1.0.3
```

**Comment by silvestreh** [comment]
Yeah, I don't think there's much I can do about that. It picks it up from `package.json` and, apparently, converts the string `#009688` to a `Color` object.
