### ISSUE TITLE
What to do to fix this?

### ISSUE THREAD

**Issue by ngthorg** [atom-material/atom-material-ui#411]
What to do to fix this?

**Screenshots and GIFs**

![screen shot 2017-05-23 at 9 38 19 am](https://cloud.githubusercontent.com/assets/4083429/26336450/c68c3d28-3f9c-11e7-8dde-b197fde9827d.png)

**Atom version:** v1.17.0 and v1.18.0-beta0
**OS and version:** macOS Sierra v10.12.5 (Hackintosh using NVIDIA GTX 960)

**Installed packages:**
- atom-material-ui
- oceanic-next

**Comment by silvestreh** [comment]
Well, you closed the issue shortly after opening it. I guess you found it's a bug in Electron 😄 … Hopefully a future release of Atom fixes this for good.
