### ISSUE TITLE
Tree view scrollbar and scrolling are disabled

### ISSUE THREAD

**Issue by supremebeing7** [atom-material/atom-material-ui#412]
When the tree view is open in Atom Material theme, scrolling vertically and horizontally using mouse scroll wheel, touchpad, or keys does not work. The scrollbar is also not visible.

I believe I have verified this is an issue with Atom Material theme. Tree view scrolling works when switching to any other theme. It also works when Atom is opened in Safe Mode.

**Reproduction Steps:**

1. Open Atom tree view
2. Ensure Atom Material theme is enabled
3. Try to scroll in the tree view pane

**Expected behavior:**

Tree view should be, and used to be, scrollable, using mouse wheel or trackpad.

**Observed behavior:**

It does not react to any scroll wheel, trackpad, or keys.

**Atom version:** 1.17.0
**OS and version:** macOS 10.12.15

**Installed packages:**

Community Packages (26)
├── Sublime-Style-Column-Selection@1.7.4
├── atom-emblem@0.3.0
├── atom-material-ui@1.3.2
├── autocomplete-ruby@0.2.8
├── autohide-tree-view@0.25.1
├── busy-signal@1.4.1
├── file-icons@2.1.6
├── guard-rspec@0.4.0
├── highlight-selected@0.13.1
├── intentions@1.1.2
├── language-rspec@0.6.2
├── language-slim@0.5.0
├── linter@2.1.4
├── linter-eslint@8.2.1
├── linter-js-yaml@1.2.7
├── linter-jsonlint@1.3.0
├── linter-reek@2.2.1
├── linter-rubocop@2.1.1
├── linter-ruby@1.2.5
├── linter-slim@1.0.0
├── linter-ui-default@1.6.0
├── markdown-preview-plus@2.4.9
├── open-in-browser@0.5.0
├── pigments@0.39.1
├── ruby-test@1.0.2
└── sync-settings@0.8.1

**Comment by supremebeing7** [comment]
I added this to my custom stylesheet and it fixes it:
```
.tree-view {
  overflow: scroll;
}
```
Not sure if this is a problem for anyone else. If it's not, I guess I can close this issue, though I'm not sure why it just started happening. It may be that an Atom update messed it up - it seems like the [new Dock feature](https://atom.io/docs/api/v1.17.0/Dock) made my tree view go haywire in a few other ways as well.

**Comment by silvestreh** [comment]
Did you upgrade to Material UI 2.0?

**Comment by supremebeing7** [comment]
😞  No. I was looking for an "Update" button in the Themes tab in Preferences. And I tried `apm update atom-material-ui` with no luck. But I just ran `apm install atom-material-ui` and it updated and the scroll bar works.

Feeling sheepish, but in my defense, it seems like if there are updates available for a theme, the Themes tab should show that?

Anyway, thanks.

**Comment by silvestreh** [comment]
Atom shows package updates in the status bar:

<img width="442" alt="captura de pantalla 2017-05-25 a la s 12 07 19" src="https://cloud.githubusercontent.com/assets/1133339/26456203/c22c917c-4142-11e7-8c7a-badf30af99a2.png">

Which will take you to the Updates section in `settings-view`

<img width="1084" alt="captura de pantalla 2017-05-25 a la s 12 07 50" src="https://cloud.githubusercontent.com/assets/1133339/26456247/e8645622-4142-11e7-8572-b9bccd1dfeda.png">

From there you can either update all packages (including themes) or just take your picks and update them individually 😄

**Comment by supremebeing7** [comment]
I _swear_ that's where I was looking and didn't see it, but it's been a long week, so 🤷‍♂️ 

Thanks!
