### ISSUE TITLE
Tree-view vertical scroll

### ISSUE THREAD

**Issue by IanCStewart** [atom-material/atom-material-ui#417]
When in the tree-view while having a project folder open you're unable to scroll down to see all your files.

**Reproduction Steps:**

1. Open a project folder
2. Try to scroll down

**Expected behavior:**

Able to scroll vertical when needed in tree-view.

**Observed behavior:**

Everything out of the view port of the tree-view is unreachable.

**Screenshots and GIFs**

![no scroll](https://cloud.githubusercontent.com/assets/14125280/26551875/eacd84d4-4484-11e7-84e8-6dd32b13e6e1.gif)

**Atom version:** 1.17.2
**OS and version:** MacOs Sierra 10.12.4

**Installed packages:**

```
├── Remote-FTP@0.10.7
├── atom-beautify@0.29.18
├── atom-live-server@2.1.2
├── atom-material-ui@1.3.9
├── busy-signal@1.3.0
├── emmet@2.4.3
├── intentions@1.1.2
├── language-babel@2.57.2
├── linter@2.1.2
├── linter-csslint@1.3.4
├── linter-eslint@8.1.5
├── linter-scss-lint@3.1.0
├── linter-ui-default@1.2.2
├── linter-xo@0.22.0
├── markdown-preview-plus@2.4.9
├── pigments@0.39.1
├── prettier-atom@0.26.0
├── seti-icons@1.4.3
└── seti-ui@1.8.0
```

**Extra styling:**

To make the tree-view usable again i added the following to my user stylesheet
```
.tool-panel.tree-view {
  overflow: auto;
}
```

**Comment by silvestreh** [comment]
Update to Material UI 2.0 😉
