### ISSUE TITLE
Background colour not covering all the window

### ISSUE THREAD

**Issue by quicoto** [atom-material/atom-material-ui#419]
Using Atom Material UI and [atom-material-syntax](https://github.com/atom-material/atom-material-syntax) on Atom 1.17.2 on MacOS 10.12.4

It seems like the background on an open is different where we have code and where we don't.

I am not sure if this is something related to the UI or the Syntax packages. Or if this is even intended to look this way.

Thank you 

![Screenshot](https://cloudup.com/c6HOX_kOs2d+)

**Comment by silvestreh** [comment]
Looks like you found https://github.com/atom/atom/issues/12634

**Comment by quicoto** [comment]
Oh, so it's core. Closing :)
