### ISSUE TITLE
tree view scroll is not work in Atom 1.7.2

### ISSUE THREAD

**Issue by zhengmin4516** [atom-material/atom-material-ui#420]
Atom : 1.7.2
macOS : 10.12.5
Atom-materal-ui : 1.3.10

when I update atom to 1.7.2 , I can't scroll in tree view with macbook touchpad .
after change to one dark theme , It works , and I change back , It's also not work.
sorry for bad english  :)

**Comment by catriuspham** [comment]
I also have this problem

**Comment by silvestreh** [comment]
Upgrade to Atom Material UI 2.0 😉
