### ISSUE TITLE
Feature Request: Option for Centering Floating Overlay-Modals on the Screen

### ISSUE THREAD

**Issue by amxmln** [atom-material/atom-material-ui#423]
Would it be possible to add an option for centering floating overlays such as the [Ctrl]+[T] modal etc. similar to how [Nord UI](https://git.io/nord-atom-ui) does it, instead of having it stuck to the top of the screen? Having to look up to the top of the screen when Atom is maximised feels like a poor user experience to me, since there’s some head and eye movement that could be saved.

![image](https://user-images.githubusercontent.com/15271679/27182176-a6f73fc6-51da-11e7-9d59-5bf4f5a7ba0e.png)

Thanks for considering this request and providing an awesome theme!

**Comment by Mehdi-Hp** [comment]
I would love that too. 👍
