### ISSUE TITLE
Can't scroll the folder list

### ISSUE THREAD

**Issue by graphpix** [atom-material/atom-material-ui#427]
There is no scroll in the folder list (left panel of atom) and it's like the panel is in overflow:hidden. We can only show the visible folders, and we can't access to the others.

**Reproduction Steps:**

1. Activate the theme

**Expected behavior:**

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Atom version:** 1.18.0
**OS and version:** OSX 10.12.5

**Installed packages:**

STFP-deployment / atom-beautify / emmet / file-icons / minimap / pigments / php-twig / platformio-ide-terminal / wordpress-api / atom-alignment

**Comment by silvestreh** [comment]
did you upgrade to Material UI 2.0?

**Comment by themakerman** [comment]
@graphpix installing using command line solved the issue for me. :).
