### ISSUE TITLE
Sidebar shadows and scroll are displayed incorrectly

### ISSUE THREAD

**Issue by SirusDoma** [atom-material/atom-material-ui#428]
Today, I installed atom material ui, however it seems displayed incorrectly.
Tho, I'm not so sure how scrollbar should look like, but the sidebar drop shadows are not the same with the screenshoot that you provide in frontpage as following figure:

![image](https://user-images.githubusercontent.com/9136829/27849109-a478380a-6174-11e7-928c-d863918fd441.png)

1. There is no drop shadow in tinted bar that separate between treeview and tabs
2. The scrollbar seems does not fit and makes the sidebar shadow aren't show
3. Sidebar shadow seems not thick as the screenshot, it's kinda look different..

Is there something I missed?
Thanks in advance

**Comment by silvestreh** [comment]
Those screenshots are from a previous version, that's why 😄

**Comment by SirusDoma** [comment]
Whoops, I don't know it was previous version.
I'm new in atom.

But somewhat I prefer how previous version look like..
Is there something I can do to get interface that match with previous version?
