### ISSUE TITLE
Custom title bar glitch

### ISSUE THREAD

**Issue by calintat** [atom-material/atom-material-ui#429]
Hello, I noticed the following UI glitch when I have "custom title bar" enabled with multiple tabs open.
Here by tabs, I mean macOS tabs as I have "Prefer tabs when opening documents" set to "always".

**Screenshots and GIFs**

![screen shot 2017-07-10 at 18 40 56](https://user-images.githubusercontent.com/16837293/28031780-5aa9e1e4-65a0-11e7-9c1e-b763d9697842.png)

**Atom version:** 1.18.0
**OS and version:** macOS 10.12.5

**Comment by silvestreh** [comment]
Looks like an issue with Atom/Electron rather than the theme … Where's that setting you mentioned?

**Comment by calintat** [comment]
This has been fixed by atom/atom#14711 so I am closing this issue.
