### ISSUE TITLE
Broken modals

### ISSUE THREAD

**Issue by Mehdi-Hp** [atom-material/atom-material-ui#430]
There is a specific type of modal which some packages use; And it's broken in atom-material-ui. See the screen shot, and for example `local-history` package, when you do the `local history: current file` command.
![screenshot from 2017-07-17 15-58-11](https://user-images.githubusercontent.com/8641684/28267403-2d8e4f5a-6b0f-11e7-92aa-7c236dc4f865.png)

**Comment by lenart** [comment]
I also have this issue (using `rails-transporter`). 

```
├── atom-material-syntax@1.0.6
├── atom-material-ui@2.0.4
```

```
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.11
git 2.14.0
```

**Comment by hendrikbl** [comment]
This seems to be an issue with some classes added to the modals select-list. See my comment at #414.

I'm not sure why/how this works with other themes, but for now you can only ask the package devs to remove these classes...
