### ISSUE TITLE
Dock toggle button glitch

### ISSUE THREAD

**Issue by nordboerg** [atom-material/atom-material-ui#434]
When there is content in the bottom dock (linter-ui-default in this case) the following glitch appears on startup. It disappears when I open and close the dock, but on startup it's always visible when the dock has been initialized.

<img width="710" alt="ui-bug" src="https://user-images.githubusercontent.com/15064779/29294463-c1e9e44c-814f-11e7-9877-44251d5a59d1.PNG">

OS: windows 10 enterprise
atom: 1.19.1

Installed packahes
├── atom-material-syntax@1.0.6
├── atom-material-ui@2.0.4
├── atom-ternjs@0.18.3 (disabled)
├── autoclose-html@0.23.0
├── autocomplete-nunjucks@0.5.0 (disabled)
├── autoprefixer@3.7.1
├── busy-signal@1.4.3
├── css-triggers@1.0.2 (disabled)
├── emmet@2.4.3
├── file-icons@2.1.10
├── git-plus@7.9.3 (disabled)
├── intentions@1.1.5
├── json-level-color@0.1.4
├── language-nunjucks@4.1.0 (disabled)
├── linter@2.2.0
├── linter-jsonlint@1.3.0
├── linter-ui-default@1.6.5
├── linter-xo@0.23.1
├── minimap@4.29.6 (disabled)
├── minimap-git-diff@4.3.1 (disabled)
├── pigments@0.40.2 (disabled)
└── sync-settings@0.8.2

**Comment by silvestreh** [comment]
This *might* be an Electron bug. Try launching Atom using `atom --enable-gpu-rasterization` and let me know if that fixed the issue.

**Comment by nordboerg** [comment]
I've tried it with the switch, it's kind of the same, but now the black rectangle is taking full width, like this:

![screenshot 13](https://user-images.githubusercontent.com/15064779/29403974-228c592e-833a-11e7-9827-f7bfcca0d6a8.png)

Also today I've noticed that the rectangle is actually not empty all the time:

![screenshot 12](https://user-images.githubusercontent.com/15064779/29404045-52e3ddf4-833a-11e7-8e90-20865c12ab4f.png)

Looks like that the content of the bottom bar is being replicated.

**Comment by silvestreh** [comment]
OK… that's weird… I'll take a look into it

**Comment by anthony-pinskey** [comment]
I get this to in Atom 1.20.0

**Comment by silvestreh** [comment]
Are you all on Windows?

**Comment by anthony-pinskey** [comment]
@silvestreh I am on macOS Sierra 10.12.5

**Comment by frontendmonster** [comment]
Same here on Atom 1.20.0
OS: windows 10

![image](https://user-images.githubusercontent.com/28571761/30493699-752ff38e-9a5a-11e7-906c-24228027c491.png)

![image](https://user-images.githubusercontent.com/28571761/30493702-7c9038be-9a5a-11e7-8c8a-eca1f828dafa.png)

**Comment by frontendmonster** [comment]
I fixed glitches by removing 'will-change' css property from scrollbar divs.
But i have no idea what i've done 🚶 

// fix dock button glitch, but it still shown when resizing tree-view 
.vertical-scrollbar div {
  will-change: inherit !important;
}

**Comment by MxRay** [comment]
Same issue here. Tested on Windows 10 and Fedora 26. Atom version both times 1.20.1 x64. Theme version 2.0.4

**Comment by Maxiride** [comment]
Same issue both below and on the side scrolling bar, will now test [this ](https://github.com/atom-material/atom-material-ui/issues/434#issuecomment-329847749)proposed workaround\fix. Running Atom for Ubuntu 16.04

![](https://i.imgur.com/cczrZEt.png)

**Comment by Algram** [comment]
I can confirm that the change from @frontendmonster fixes the issue for me on Fedora 26.

**Comment by vladimir-didenko** [comment]
Change from @frontendmonster fix dock but breaks scroll bar like in https://github.com/atom-material/atom-material-ui/issues/442 .
