### ISSUE TITLE
White flashes on atom after using this ui

### ISSUE THREAD

**Issue by mihirsam** [atom-material/atom-material-ui#435]
[Short description of problem here]

**Reproduction Steps:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Atom version:** [Enter Atom version here]
**OS and version:** [Enter OS name and version here]

**Installed packages:**

[List of installed packages here]

**Comment by silvestreh** [comment]
Closing due to not having any useful information on the issue
