### ISSUE TITLE
Text in modal overlay text field is really small

### ISSUE THREAD

**Issue by lokesh-krishna** [atom-material/atom-material-ui#440]
Text in modal overlay text field is really small

**Reproduction Steps:**

1. Open modal overlay (command palette or new file)
2. Enter text in the text field at the top of the overlay
3. Font size is too small to be able to read conveniently

**Expected behavior:**
Font size would match that of the rest of the overlay and maybe even belong to the same font-family like in Nord.

**Screenshots and GIFs**

Here are the modal overlays from Material UI: 

![screenshot from 2017-10-03 07-18-21](https://user-images.githubusercontent.com/20235646/31106775-8d465864-a80b-11e7-8138-2758089c1ebe.png)
![screenshot from 2017-10-03 07-18-28](https://user-images.githubusercontent.com/20235646/31106776-8d7cc674-a80b-11e7-860e-073c73843175.png)

For contrast, here are the modal overlays from Nord UI.

![screenshot from 2017-10-03 07-27-23](https://user-images.githubusercontent.com/20235646/31106936-a9a6d0f0-a80c-11e7-9e06-f6ef5aeacec6.png)
![screenshot from 2017-10-03 07-28-21](https://user-images.githubusercontent.com/20235646/31106935-a969e438-a80c-11e7-881e-6f4a9b913560.png)

**Atom version:** 1.20.0
**OS and version:** Fedora 26 Workstation

**Installed packages:**

atom-material-syntax
atom-material-ui
file-type-icons
nord-atom-syntax
nord-atom-ui
typewriter
wordcount
Zen

**Comment by OriginalFannibal** [comment]
I fixed it for myself by adding the following to my stylesheet:

```
// Style the mini editor for modal overlays
atom-text-editor.mini {
  font-size: 16px;
 font-family: inherit;
  }

```

This is what the text in the mini editor looks like now:

![screenshot from 2017-10-03 10-24-30](https://user-images.githubusercontent.com/20235646/31110487-120ab8ec-a825-11e7-8e6b-da1de11dbbb7.png)

If you think this is an issue then I would like to submit a PR for this.
