### ISSUE TITLE
Top modal broken in Atom when using atom-material-ui

### ISSUE THREAD

**Issue by kikoking** [atom-material/atom-material-ui#444]
Hey,

So I have been noticing this for a while now and I guess was just hoping it would go away on its own but hasn't.

When I use the atom-commander plugin to edit ftp credentials (or any plugin that drops down the top modal in Atom) the top modal doesn't drop down like it is supposed to and, in affect, is broken. It took me forever to figure out what was causing it as I thought it was the atom-commander plugin. Eventually I wiped Atom completely and found that the top modal was working again, and with atom-commander. It was only when I starting using the atom-material-ui again that it stopped working. I've done some more thorough testing and confirmed that it is the atom-material-ui plugin that is the issue, when it is active.

I very much enjoy this plugin and am very glad you made it, but I can't effectively use it in my work flow with this bug. Are you able to please fix it?

**Comment by silvestreh** [comment]
Can you please share screenshots of the expected and current (broken) behavior?

**Comment by kikoking** [comment]
Right click on the left or right pane and select Servers > Edit. You should get this issue - 

Undesired behaviour -

![undesired](https://user-images.githubusercontent.com/17826852/31405213-3e6feac2-adb3-11e7-933b-56472f198615.png)

Desired behaviour -

![desired](https://user-images.githubusercontent.com/17826852/31405235-4b1e8e36-adb3-11e7-83eb-1d4464115f91.png)

I'm using Atom version 1.20.1 for mac. I'm using the latest version of atom-commander 0.10.2, and atom-material-ui 2.0.5

So to clarify, I guess it isn't just the top modal, but whenever I try to edit the ftp settings with atom commander (I have had the same problem with other remote ftp editors like remote-edit as well).

**Comment by hendrikbl** [comment]
This seems to be an issue with some classes added to the modals select-list. See my comment for #414.

You should probably create an issue for `atom-commander` so they can change it.
