### ISSUE TITLE
Compact Tree View 

### ISSUE THREAD

**Issue by vtempest** [atom-material/atom-material-ui#446]
Please have option so tree view items have less padding, perhaps proportional to font size, since in most other themes you can see way more onscreen on the sidebar at once and less scroll. I have implemented a solution that makes the Tree View Compact

Click on atom-material-ui settings in Themes. Click on View Code. Put this into styles/ui-variables.less line 76 replacing the existing code and restart
```
@font-size: 16px;
@input-font-size: 16px;
@disclosure-arrow-size: 12px;
@component-padding: 6px;
@component-icon-padding: 3px;
@component-icon-size: 10px;
@component-line-height: 20px;
@component-border-radius: .125rem;
@tab-height: 2.5rem;
@compact-tab-height: 2rem;
```

**Comment by silvestreh** [comment]
And on the next update you'll have these overwritten 😄 … It's best to use your user stylesheet.

**Comment by bmatto** [comment]
Did the option to have compact tree view get removed from the package?

**Comment by silvestreh** [comment]
Yes, it did.

**Comment by flowerjun** [comment]
Please try again...

**Comment by mrleblanc101** [comment]
@silvestreh Why did it got removed ? The tree view padding for each file/folder is HUGE !
It seem weird to me that atom-material-ui offer a compact tab bar that shave 0.5rem from m=the tab bar but not a compact tree view that could save hundred of pixel allowing you to see more file/folder without scrolling.

**Comment by ConnorIngold** [comment]
Did anybody find a workaround for this?
