### ISSUE TITLE
Notifications broken in latest Atom beta

### ISSUE THREAD

**Issue by Arcanemagus** [atom-material/atom-material-ui#454]
Notification styling appears to have broken in the current v1.24.0-beta0 beta, let me know if I should file this on Atom instead!

**Reproduction Steps:**

1. Install Atom v1.24.0-beta0
2. Open the Developer Console
3. Run this code:
  ```js
  atom.notifications.addSuccess("Foobar", { buttons: [{ text: "Click me" }], dismissable: true })
  ```

**Expected behavior:**

Notifications look consistent.

**Observed behavior:**

Notification buttons are barely readable, and there is a large bar on the side of the background color.

**Screenshots and GIFs**
One Dark:
![image](https://user-images.githubusercontent.com/427137/33900247-ad4ac002-df22-11e7-98fc-6a130e8447a1.png)

Atom Material UI (+ One Dark syntax + Green predefined colors):
![image](https://user-images.githubusercontent.com/427137/33900269-bbfbdac8-df22-11e7-831a-bda8f4f717b8.png)

**Atom version:**
```
Atom    : 1.24.0-beta0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**OS and version:**
Windows 10 x64 Enterprise

**Installed packages:**

<details>
<summary>Installed packages</summary>

```
Community Packages (79) C:\Users\abneyl\.atom\packages
├── atom-beautify@0.30.9
├── atom-ide-ui@0.6.0
├── atom-material-ui@2.0.6
├── autocomplete-lua@0.9.0
├── busy-signal@1.4.3 (disabled)
├── docblockr@0.13.3
├── editorconfig@2.2.2
├── file-watcher@1.2.6 (disabled)
├── highlight-selected@0.13.1
├── ide-flowtype@0.17.4
├── ide-php@0.7.4
├── ide-python@0.3.0
├── ide-typescript@0.7.1
├── intentions@1.1.5 (disabled)
├── language-ansible@0.2.1
├── language-chef@0.11.0
├── language-cjson@0.0.1
├── language-docker@1.1.8
├── language-elixir@0.20.3
├── language-erlang@3.2.0
├── language-fortran@2.1.6
├── language-gettext@0.6.1
├── language-glsl@2.0.4
├── language-haml@0.25.2
├── language-haskell@1.15.0
├── language-icinga2@0.3.0
├── language-ini@1.19.0
├── language-jade@0.7.2
├── language-jolie@0.5.0
├── language-kotlin@0.5.0
├── language-livescript@0.0.3
├── language-lua@0.9.11
├── language-moonscript@1.7.1
├── language-postcss@1.3.1
├── language-powershell@4.0.0
├── language-puppet@0.23.0
├── language-r@0.4.2
├── language-reg@0.0.0
├── language-rust@0.4.12
├── language-swift@0.5.0
├── language-terraform@0.8.1
├── language-vue@0.23.1
├── linter@2.2.0 (disabled)
├── linter-coffeelint@1.3.1
├── linter-eslint@8.4.0
├── linter-flake8@2.3.0
├── linter-htmlhint@1.4.0
├── linter-js-standard@4.1.0
├── linter-js-yaml@1.2.8
├── linter-jsonlint@1.3.0
├── linter-markdown@5.2.0
├── linter-perl@0.8.1
├── linter-perlcritic@2.0.0
├── linter-php@1.5.1
├── linter-phpcs@1.6.8
├── linter-phpmd@2.0.0
├── linter-proselint@3.3.0
├── linter-pylama@0.9.5
├── linter-pylint@2.1.0
├── linter-rails-best-practices@0.2.2 (disabled)
├── linter-reek@2.2.2
├── linter-rubocop@2.2.0
├── linter-ruby@1.2.6
├── linter-stylelint@4.1.0
├── linter-tidy@2.3.1
├── linter-ui-default@1.6.10 (disabled)
├── linter-ui-plus@0.3.2 (disabled)
├── mapfile-grammar@0.1.0
├── minimap@4.29.7
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-linter@2.1.3
├── minimap-selection@4.5.0
├── sequential-number@0.5.0
├── sort-lines@0.18.0
├── tab-control@0.6.10
├── teletype@0.3.0
├── toggle-quotes@1.1.0
└── trailing-spaces@0.4.0
```

</details>

**Comment by pingshunhuangalex** [comment]
And this seems to be a Windows only issue.

**Comment by pingshunhuangalex** [comment]
@silvestreh I just updated the package to `2.1.0` and tested on `1.24.0-beta1` and `1.24.0-beta2`. Unfortunately, this issue persists.

**Comment by silvestreh** [comment]
Because it's fixed in the repo, not the published version. Once 1.24 reaches the stable channel I'll push a patch to APM

**Comment by pingshunhuangalex** [comment]
@silvestreh Sorry for the spamming. It seems like with the latest version. There is still a bit of issues with tall notification toasters.
![screen shot 2018-01-10 at 8 54 37 am](https://user-images.githubusercontent.com/17170199/34745353-54a0f344-f5e4-11e7-82ca-567a6f541cab.png)
