### ISSUE TITLE
Last line is halved horizontally

### ISSUE THREAD

**Issue by drorata** [atom-material/atom-material-ui#457]
When reaching the bottom of the pane, the lowest line is halved along a horizontal line.

**Reproduction Steps:**

1. Hit `enter` until reaching to the bottom of the pane
2. Start typing

**Expected behavior:**

The last line should be fully visible.

**Observed behavior:**

The very last line is partially visible; only the upper half of it.

**Screenshots and GIFs**

![problem](https://user-images.githubusercontent.com/2905978/34521005-b9b40612-f08b-11e7-80b3-68a4cdab8b89.gif)

**Atom version:** 1.23.2
**OS and version:** macOS 10.13.2

**Installed packages:**

```
advanced-open-file@0.16.7
atom-beautify@0.30.9
atom-material-syntax@1.0.8
atom-material-ui@2.1.0
autocomplete-python@1.10.5
busy-signal@1.4.3
center-line@1.2.4
compare-files@0.8.1
custom-title@1.0.1
data-atom@0.26.2
export-html@3.1.0
file-icons@2.1.15
fold-functions@0.5.0
git-plus@7.10.0
highlight-line@0.12.0
highlight-selected@0.13.1
intentions@1.1.5
language-docker@1.1.8
language-ini@1.19.0
language-latex@1.1.1
language-restructuredtext@1.1.0
language-terraform@0.8.1
linter@2.2.0
linter-flake8@2.3.0
linter-js-yaml@1.2.8
linter-ui-default@1.6.10
markdown-preview-enhanced@0.15.1
markdown-toc@0.4.2
markdown-writer@2.7.3
minimap@4.29.7
minimap-highlight-selected@4.6.1
multi-cursor@2.1.5
platformio-ide-terminal@2.8.0
pretty-json@1.6.4
python-indent@1.1.4
script@3.17.3
select-rectangle@1.0.2
split-diff@1.5.2
sync-settings@0.8.3
tablr@1.8.3
```

**Comment by Songworks** [comment]
Having the same issue since 2.1.0 update.
Additionally to that, the Diagnostics panel of `atom-ide-ui` has an input fields placeholder (Filter) halved also:
![1]

[1]: https://imgur.com/63vcLyg.png

Neither happens with version 2.0.6.

**Atom version**: 1.23.1
**OS version**: Linux Mint 17.3

**Installed packages**:
Tried and reproduced issue with clean Atom profile and only `atom-material-ui` installed

**Comment by silvestreh** [comment]
Done! A patch should be avaialble any minute now
