### ISSUE TITLE
Reduce Indent in Side Panel

### ISSUE THREAD

**Issue by bgarrant** [atom-material/atom-material-ui#458]
I am using latest Atom 1.23.2 and Material UI.  How can I reduce the indent in the sidebar a bit?

![screen shot 2018-01-09 at 3 13 35 pm](https://user-images.githubusercontent.com/2436728/34741146-b4523ef0-f54f-11e7-9d30-406adb36e7bc.png)

**Comment by bgarrant** [comment]
One Dark has a nice Indent amount

![screen shot 2018-01-09 at 3 14 36 pm](https://user-images.githubusercontent.com/2436728/34741219-e3f29c90-f54f-11e7-9412-660ecc545b60.png)

**Comment by silvestreh** [comment]
It's not the indentation, but the icon's horizontal margin. Try fiddling with it in your user stylesheet.

**Comment by bgarrant** [comment]
I am not sure what styles need to be modified for the icons.  Can you advise?

**Comment by bgarrant** [comment]
I figured how to manually do this, but do you plan to have a Compact Tree View in future release?

**Comment by silvestreh** [comment]
Just implemented the compact tree view option. I'll create a new release after I test it some more on Atom Beta

**Comment by bgarrant** [comment]
Sounds great.  Can't wait to try it out.  Thanks again.

**Comment by bgarrant** [comment]
Did you release it already?  I have latest version 2.1.3 and I do not see the option if so.

**Comment by silvestreh** [comment]
no, not yet. I'm not quite happy with the current implementation
