### ISSUE TITLE
Package update clears user's configuration

### ISSUE THREAD

**Issue by PapsOu** [atom-material/atom-material-ui#464]
When updating the package with atom, the user configuration is lost and is overriden by the default configuration provided by the package.

**Reproduction Steps:**

1. Install the theme package
2. Change primary and/or secondary color
3. Update the package

**Expected behavior:**

User's custom configuration (primary and secondary colors) should not be changed

**Observed behavior:**

Primary and secondary color are reset to defaults ones (teal and dark gray).

This unexpected behaviour is seen with `atom-material-ui@2.1.3` and a previous version `atom-material-ui@2.1.2`.

**Atom version:**
```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
**OS and version:** 

```fedora 27 | 4.14.18-300.fc27.x86_64```
```ubuntu 16.04 | 4.4.0-112-generic```

**Installed packages:** (apm list --installed --bare)
```
atom-autocomplete-php@0.25.6
atom-beautify@0.30.9
atom-material-syntax@1.0.8
atom-material-syntax-dark@1.0.0
atom-material-ui@2.1.3
atom-rst-preview-docutils@1.0.0
atom-watcher@1.1.7
autoclose-html@0.23.0
bookmarks@0.45.1
bright-dark-syntax@0.4.1
browser-plus@0.0.98
dash-ui@0.4.4
docblockr@0.13.6
editorconfig@2.2.2
file-type-icons@1.3.4
fold-functions@0.5.0
fonts@3.0.3
git-control@0.9.0
git-difftool@0.2.7
git-plus@7.10.0
git-time-machine@1.5.9
goto-definition@1.3.4
highlight-selected@0.13.1
intentions@1.1.5
language-docker@1.1.8
language-htaccess@0.2.0
language-markdown@0.25.1
language-restructuredtext@1.1.0
linter@2.2.0
linter-php@1.5.1
linter-ui-default@1.6.10
markdown-table-editor@1.0.2
minimap@4.29.7
minimap-git-diff@4.3.1
minimap-highlight-selected@4.6.1
multi-cursor@2.1.5
open-unsupported-files@1.0.20
pandoc-convert@1.1.1
php-getters-setters@0.5.5
php-twig@4.0.0
pigments@0.40.2
project-manager@3.3.5
quick-query@0.12.2
rest-client@1.3.1
rst-snippets@1.1.5
sort-lines@0.18.0
sphinx-preview@0.1.1
split-diff@1.5.2
teletype@0.8.0
text-manipulation@0.6.0
```

**Comment by Tawreh** [comment]
Have found the same issue, and I'm unable to reset to the colour I had chosen previously.

```
$ apm list --installed --bare 
atom-autocomplete-php@0.25.6
atom-material-ui@2.1.3
busy-signal@1.4.3
docblockr@0.13.6
intentions@1.1.5
language-markdown@0.25.1
linter@2.2.0
linter-drupalcs@1.4.1
linter-ui-default@1.6.10
php-debug@0.2.6
php-twig@4.0.0
pigments@0.40.2
seti-ui@1.10.0
```

**Comment by ivogomes** [comment]
Same problem here. No matter which color you chose, it stays with the default teal color

**Comment by silvestreh** [comment]
I can't seem reproduce this

**Comment by rcxr** [comment]
I am having the same issue. I have found that this only reproduces when using the combination:
atom-material-ui + atom-material-syntax-dark

Custom configuration works fine with any other combination, including:
atom-material-ui + atom-material-syntax

This is not a valid work-around for me as I don't like the atom-material-syntax theme 😛

**Comment by vinnymac** [comment]
This has always happened for me whenever updating, and I had just assumed it was an issue with atom. Reloading using the keyboard shortcut above doesn't fix the issue for me. However, 100% of the time if I quit atom and reopen it, it will fix the settings issue.

![atommaterialuibug](https://user-images.githubusercontent.com/1832781/37568557-1324a61a-2aad-11e8-8d1b-ca336e55fc2b.gif)
