### ISSUE TITLE
Vibrant-ink syntax theme misidentified as light by material-ui's adaptive theming

### ISSUE THREAD

**Issue by Digital-ecologist** [atom-material/atom-material-ui#473]
[Atom-material-ui 2.1.3 treats vibrant-Ink 1.0.4 as a light syntax theme, when it is actually dark.]

**Reproduction Steps:**

1. [With the syntax theme set to monokai-seti0.9 0 Atom-material-ui themes perfectly.]
![atom-material and monokai-seti jpg](https://user-images.githubusercontent.com/42946430/45638292-cb09e580-ba7a-11e8-8cc2-26bcf4099ca9.jpg)

2. [Changing the syntax theme to vibrant-Ink 1.0.4 causes the theme to"adapt" to a bright white variant.]
![atom-material and vibrant-ink jpg](https://user-images.githubusercontent.com/42946430/45638320-e07f0f80-ba7a-11e8-8e82-c0e4cc5eacc4.jpg)

**Expected behavior:**

[The UI theme should not change at all, when switching between monokai-seti 0.9 0 and vibrant-Ink 1.0.4 because both are dark syntax themes.]

**Observed behavior:**

[Changing the syntax theme to vibrant-Ink 1.0.4 causes the theme to"adapt" to a bright white variant.]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Atom version:** [1.30.0]
**OS and version:** [Windows 7 Home Premium 64-bit]

**Installed packages:**

[Built-in Atom Packages (92)
├── atom-dark-syntax@0.29.0
├── atom-dark-ui@0.53.2
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.2
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.12.4
├── one-light-ui@1.12.4
├── one-dark-syntax@1.8.4
├── one-light-syntax@1.8.4
├── solarized-dark-syntax@1.1.5
├── solarized-light-syntax@1.1.5
├── about@1.10.0
├── archive-view@0.65.1
├── autocomplete-atom-api@0.10.7
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.4
├── autocomplete-plus@2.40.7
├── autocomplete-snippets@1.12.0
├── autoflow@0.29.4
├── autosave@0.24.6
├── background-tips@0.28.0
├── bookmarks@0.45.1
├── bracket-matcher@0.89.2
├── command-palette@0.43.5
├── dalek@0.2.2
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.9
├── exception-reporting@0.43.1
├── find-and-replace@0.215.12
├── fuzzy-finder@1.8.2
├── github@0.18.3
├── git-diff@1.3.9
├── go-to-line@0.33.0
├── grammar-selector@0.50.1
├── image-view@0.63.0
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.2
├── line-ending-selector@0.7.7
├── link@0.31.4
├── markdown-preview@0.159.20
├── metrics@1.6.1
├── notifications@0.70.5
├── open-on-github@1.3.1
├── package-generator@1.3.0
├── settings-view@0.255.0
├── snippets@1.3.3
├── spell-check@0.74.0
├── status-bar@1.8.15
├── styleguide@0.49.11
├── symbols-view@0.118.2 (disabled)
├── tabs@0.109.2
├── timecop@0.36.2
├── tree-view@0.222.0
├── update-package-dependencies@0.13.1
├── welcome@0.36.6
├── whitespace@0.37.6
├── wrap-guide@0.40.3
├── language-c@0.60.0
├── language-clojure@0.22.7
├── language-coffee-script@0.49.3
├── language-csharp@1.0.4
├── language-css@0.42.11
├── language-gfm@0.90.5
├── language-git@0.19.1
├── language-go@0.46.0
├── language-html@0.51.1
├── language-hyperlink@0.16.3
├── language-java@0.30.0
├── language-javascript@0.129.1
├── language-json@0.19.2
├── language-less@0.34.2
├── language-make@0.22.3
├── language-mustache@0.14.5
├── language-objective-c@0.15.1
├── language-perl@0.38.1
├── language-php@0.44.0
├── language-property-list@0.9.1
├── language-python@0.51.2
├── language-ruby@0.72.2
├── language-ruby-on-rails@0.25.3
├── language-sass@0.62.0
├── language-shellscript@0.27.0
├── language-source@0.9.0
├── language-sql@0.25.10
├── language-text@0.7.4
├── language-todo@0.29.4
├── language-toml@0.18.2
├── language-typescript@0.4.0
├── language-xml@0.35.2
└── language-yaml@0.32.0

Community Packages (26) C:\Users\Austin\.atom\packages
├── ask-stack@2.2.0
├── atom-beautify@0.33.1
├── atom-ctags@5.1.2
├── atom-ide-ui@0.13.0
├── atom-material-ui@2.1.3
├── busy-signal@1.4.3
├── file-icons@2.1.24
├── highlight-selected@0.14.0
├── Hydrogen@2.6.0
├── hydrogen-launcher@1.2.2
├── hydrogen-python@0.0.7
├── ide-python@1.0.0
├── ide-r@0.1.8
├── intentions@1.1.5
├── language-r@0.4.2
├── linter@2.2.0 (disabled)
├── linter-lintr@1.1.4
├── linter-ui-default@1.7.1
├── monokai-seti@0.9.0
├── neon-syntax@0.3.7
├── nord-atom-ui@0.11.0
├── pigments@0.40.2
├── platformio-ide-terminal@2.8.4
├── rbox@0.5.0
├── termination@0.6.3
└── vibrant-ink@1.0.4]

**Comment by silvestreh** [comment]
It's because the syntax theme isn't exposing syntax variables. You can [check this old PR](https://github.com/carloe/spacegray-base16-ocean-dark/pull/13) I submitted to a syntax theme with the same issue and inform the syntax theme maintainer.
